<div class="row g-3">
    <div class="col-12"><label for="service_id" class="form-label">Service</label><select id="service_id" name="service_id" class="form-select @error('service_id') is-invalid @enderror" required><option value="">Select a service</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string) old('service_id', $document?->service_id ?? request('service_id')) === (string) $service->id)>{{ $service->name_en }} / {{ $service->name_gu }}</option>@endforeach</select>@error('service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label for="name_gu" class="form-label">Gujarati Name</label><input id="name_gu" name="name_gu" value="{{ old('name_gu', $document?->name_gu) }}" class="form-control @error('name_gu') is-invalid @enderror" required>@error('name_gu')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label for="name_en" class="form-label">English Name</label><input id="name_en" name="name_en" value="{{ old('name_en', $document?->name_en) }}" class="form-control @error('name_en') is-invalid @enderror" required>@error('name_en')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label for="sort_order" class="form-label">Display Order</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $document?->sort_order ?? 0) }}" class="form-control" required></div>
    <div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="is_mandatory" value="0"><input id="is_mandatory" name="is_mandatory" type="checkbox" value="1" class="form-check-input" @checked(old('is_mandatory', $document?->is_mandatory ?? true))><label for="is_mandatory" class="form-check-label">Required document</label></div></div>
    <div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="is_active" value="0"><input id="is_active" name="is_active" type="checkbox" value="1" class="form-check-input" @checked(old('is_active', $document?->is_active ?? true))><label for="is_active" class="form-check-label">Active on public website</label></div></div>
</div>
<div class="mt-4 d-flex gap-2"><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.required-documents.index') }}">Cancel</a></div>
