@extends('layouts.admin')
@section('title', 'Required Documents')
@section('content')
<h1 class="h3">Central Required Documents Master</h1>
<p class="text-muted">Master names are shared. Requirement state and order are configured independently for each service.</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card card-body mb-4"><form method="POST" action="{{ route('admin.required-document-master.store') }}">@csrf<div class="row g-2"><div class="col-md-2"><input name="code" class="form-control" placeholder="stable-code" required></div><div class="col-md-3"><input name="name_gu" class="form-control" placeholder="Gujarati name" required></div><div class="col-md-3"><input name="name_en" class="form-control" placeholder="English name" required></div><div class="col-md-2"><input name="display_order" type="number" min="0" value="{{ $masters->count()+1 }}" class="form-control" required></div><div class="col-md-1"><input type="hidden" name="is_active" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked> Active</label></div><div class="col-md-1"><button class="btn btn-primary">Add</button></div></div></form></div>
<div class="card mb-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Order</th><th>Code</th><th>Gujarati</th><th>English</th><th>Active</th><th></th></tr></thead><tbody>@foreach($masters as $master)<tr><td>{{ $master->display_order }}</td><td><code>{{ $master->code }}</code></td><td>{{ $master->name_gu }}</td><td>{{ $master->name_en }}</td><td>{{ $master->is_active ? 'Yes' : 'No' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.required-document-master.edit',$master) }}">Edit</a></td></tr>@endforeach</tbody></table></div></div>
<form method="GET" class="card card-body mb-3"><div class="row g-2 align-items-end"><div class="col-md-6"><label class="form-label">Configure service mappings</label><select name="service_id" class="form-select"><option value="">Select service</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string)request('service_id')===(string)$service->id)>{{ $service->name_en }} / {{ $service->name_gu }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary">Load</button></div></div></form>
@if(request('service_id'))
@php($selectedService=$services->firstWhere('id',(int)request('service_id')))
@if($selectedService)<form method="POST" action="{{ route('admin.required-documents.mappings.update',$selectedService) }}">@csrf @method('PUT')<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Document</th><th>Requirement Type</th><th>Display Order</th><th>Active</th></tr></thead><tbody>@foreach($documents->getCollection()->where('service_id',$selectedService->id) as $document)<tr><td><strong>{{ $document->name_gu }}</strong><div class="text-muted small">{{ $document->name_en }}</div></td><td><select class="form-select" name="mappings[{{ $document->id }}][requirement_type]">@foreach(['required'=>'Required / ફરજિયાત','optional'=>'Optional / વૈકલ્પિક','any_one_required'=>'Any One Required / આમાંથી કોઈ એક જરૂરી','not_applicable'=>'Not Applicable / લાગુ નથી'] as $value=>$label)<option value="{{ $value }}" @selected($document->requirement_type===$value)>{{ $label }}</option>@endforeach</select></td><td><input class="form-control" type="number" min="0" name="mappings[{{ $document->id }}][sort_order]" value="{{ $document->sort_order }}"></td><td>{{ $document->requirement_type==='not_applicable' ? 'No' : 'Yes' }}</td></tr>@endforeach</tbody></table></div><div class="card-body"><button class="btn btn-primary">Save Mappings</button></div></div></form>@endif
@endif
@endsection
