@extends('layouts.admin')
@section('title', 'Required Documents')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Service Required Documents</h1><p class="text-muted mb-0">Manage documents shown for each service.</p></div><a class="btn btn-primary" href="{{ route('admin.required-documents.create') }}">Add Document</a></div>
<form method="GET" class="card card-body mb-3"><div class="row g-2"><div class="col-lg-5"><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Search document or service"></div><div class="col-lg-3"><select name="service_id" class="form-select"><option value="">All services</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string) request('service_id') === (string) $service->id)>{{ $service->name_en }}</option>@endforeach</select></div><div class="col-lg-2"><select name="active" class="form-select"><option value="">All statuses</option><option value="1" @selected(request('active') === '1')>Active</option><option value="0" @selected(request('active') === '0')>Inactive</option></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-outline-primary">Search</button><a href="{{ route('admin.required-documents.index') }}" class="btn btn-outline-secondary">Clear</a></div></div></form>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @error('documents')<div class="alert alert-danger">{{ $message }}</div>@enderror
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Order</th><th>Document</th><th>Service</th><th>Type</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($documents as $document)<tr><td>{{ $document->sort_order }}</td><td><strong>{{ $document->name_gu }}</strong><div class="small text-muted">{{ $document->name_en }}</div></td><td>{{ $document->service->name_en }}</td><td><span class="badge {{ $document->is_mandatory ? 'text-bg-danger' : 'text-bg-info' }}">{{ $document->is_mandatory ? 'Required' : 'Optional' }}</span></td><td><span class="badge {{ $document->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $document->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><div class="d-inline-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.required-documents.edit', $document) }}">Edit</a><form method="POST" action="{{ route('admin.required-documents.destroy', $document) }}" onsubmit="return confirm('Delete this document? Used documents will be archived.')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-5">No required documents found.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $documents->links() }}</div>
@if(request('service_id') && $documents->count())<form method="POST" action="{{ route('admin.required-documents.reorder', request('service_id')) }}" class="card card-body mt-3">@csrf @method('PATCH')<h2 class="h5">Reorder filtered service</h2><p class="small text-muted">Enter document IDs in the desired order.</p><div class="input-group"><input id="document_order" class="form-control" value="{{ $documents->pluck('id')->implode(',') }}"><button class="btn btn-outline-primary" type="button" id="save-order">Save Order</button></div><div id="order-fields"></div></form>@endif
@endsection
@push('scripts')<script>document.getElementById('save-order')?.addEventListener('click',function(){const form=this.form,container=document.getElementById('order-fields');container.replaceChildren();document.getElementById('document_order').value.split(',').map(v=>v.trim()).filter(Boolean).forEach(id=>{const input=document.createElement('input');input.type='hidden';input.name='documents[]';input.value=id;container.append(input)});form.submit()});</script>@endpush
