@extends('layouts.admin')
@section('title', 'Add Offline Request')
@section('breadcrumbs')<li class="breadcrumb-item"><a href="{{ route('admin.requests.index') }}">Requests</a></li><li class="breadcrumb-item active">Add Offline Request</li>@endsection
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h2 mb-1">Add Offline Request</h1><p class="text-muted mb-0">Record a walk-in or manually received customer request.</p></div><a href="{{ route('admin.requests.index') }}" class="btn btn-outline-secondary align-self-md-start">Back to Requests</a></div>
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please correct the highlighted fields.</strong></div>@endif
<form method="POST" action="{{ route('admin.requests.store') }}" enctype="multipart/form-data">@csrf
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Customer Information</div><div class="card-body"><div class="row g-3">
        <div class="col-md-6"><label for="name" class="form-label">Name</label><input id="name" name="name" value="{{ old('name') }}" maxlength="100" required class="form-control @error('name') is-invalid @enderror">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="mobile" class="form-label">Mobile</label><input id="mobile" name="mobile" value="{{ old('mobile') }}" inputmode="numeric" maxlength="10" required class="form-control @error('mobile') is-invalid @enderror">@error('mobile')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="email" class="form-label">Email <span class="text-muted">(optional)</span></label><input id="email" type="email" name="email" value="{{ old('email') }}" maxlength="255" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label for="address" class="form-label">Address</label><textarea id="address" name="address" rows="3" maxlength="1000" required class="form-control @error('address') is-invalid @enderror">{{ old('address') }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Service & Property Information</div><div class="card-body"><div class="row g-3">
        <div class="col-12"><label for="service_id" class="form-label">Service</label><select id="service_id" name="service_id" required class="form-select @error('service_id') is-invalid @enderror"><option value="">Select Service</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string)old('service_id') === (string)$service->id)>{{ $service->name_en }} / {{ $service->name_gu }}</option>@endforeach</select>@error('service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="survey_numbers" class="form-label">Survey Number</label><input id="survey_numbers" name="survey_numbers" value="{{ old('survey_numbers') }}" maxlength="1000" required class="form-control @error('survey_numbers') is-invalid @enderror">@error('survey_numbers')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="khata_number" class="form-label">Khata Number</label><input id="khata_number" name="khata_number" value="{{ old('khata_number') }}" maxlength="100" required class="form-control @error('khata_number') is-invalid @enderror">@error('khata_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label for="details" class="form-label">Details</label><textarea id="details" name="details" rows="4" maxlength="2000" required class="form-control @error('details') is-invalid @enderror">{{ old('details') }}</textarea>@error('details')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Documents</div><div class="card-body"><label for="documents" class="form-label">Upload property documents</label><input id="documents" type="file" name="documents[]" multiple required accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" class="form-control @error('documents') is-invalid @enderror @error('documents.*') is-invalid @enderror"><div class="form-text">Maximum 10 files, 10 MB each. PDF, JPG, JPEG and PNG only. Do not upload Aadhaar or PAN documents.</div>@error('documents')<div class="invalid-feedback">{{ $message }}</div>@enderror @error('documents.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
    <div class="d-flex justify-content-end gap-2"><a href="{{ route('admin.requests.index') }}" class="btn btn-outline-secondary">Cancel</a><button type="submit" class="btn btn-success">Create Offline Request</button></div>
</form>
@endsection
