@extends('layouts.admin')
@section('title','Customer Requests')
@section('breadcrumbs')<li class="breadcrumb-item active">Requests</li>@endsection
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h2 mb-1">Customer Requests</h1><p class="text-muted mb-0">Search, review and manage submitted requests.</p></div><div class="d-flex flex-wrap align-items-center gap-2"><span class="badge text-bg-primary fs-6">{{ $requests->total() }} requests</span><a href="{{ route('admin.requests.create') }}" class="btn btn-success">Add Offline Request</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form class="card border-0 shadow-sm mb-4" method="GET"><div class="card-body"><div class="row g-3">
<div class="col-lg-4"><label for="request-search" class="form-label">Search</label><input id="request-search" name="q" value="{{ request('q') }}" class="form-control" placeholder="Reference, file, customer, mobile or service"></div>
<div class="col-sm-6 col-lg-2"><label for="request-village" class="form-label">Village</label><input id="request-village" name="village" value="{{ request('village') }}" class="form-control"></div>
<div class="col-sm-6 col-lg-2"><label for="request-survey" class="form-label">Survey Number</label><input id="request-survey" name="survey_number" value="{{ request('survey_number') }}" class="form-control"></div>
<div class="col-sm-6 col-lg-2"><label for="request-khata" class="form-label">Khata Number</label><input id="request-khata" name="khata_number" value="{{ request('khata_number') }}" class="form-control"></div>
<div class="col-sm-6 col-lg-2"><label for="request-processing-stage" class="form-label">Processing Stage</label><input id="request-processing-stage" name="processing_stage" value="{{ request('processing_stage') }}" class="form-control" placeholder="e.g. drafting"></div>
<div class="col-sm-6 col-lg-2"><label for="request-source" class="form-label">Source</label><select id="request-source" name="source" class="form-select"><option value="">All</option><option value="online" @selected(request('source')==='online')>Online</option><option value="offline" @selected(request('source')==='offline')>Offline</option></select></div>
<div class="col-sm-6 col-lg-2"><label for="request-status" class="form-label">Status</label><select id="request-status" name="status" class="form-select"><option value="">All</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label for="request-processing" class="form-label">Processing</label><select id="request-processing" name="processing_state" class="form-select"><option value="">All</option>@foreach(['not_started'=>'Processing Not Started','in_progress'=>'In Progress','ready'=>'Ready to Complete','completed'=>'Completed'] as $value=>$label)<option value="{{ $value }}" @selected(request('processing_state')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label for="request-dispatch" class="form-label">Dispatch</label><select id="request-dispatch" name="dispatch_state" class="form-select"><option value="">All</option>@foreach(['pending'=>'Completed – Dispatch Pending','dispatched'=>'Dispatched','in_transit'=>'In Transit','delivered'=>'Delivered / Collected','ready_to_close'=>'Ready to Close','closed'=>'Closed','failed_returned'=>'Failed / Returned'] as $value=>$label)<option value="{{ $value }}" @selected(request('dispatch_state')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label for="request-service" class="form-label">Service</label><select id="request-service" name="service_id" class="form-select"><option value="">All</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string)request('service_id')===(string)$service->id)>{{ $service->name_en }}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label for="request-date-from" class="form-label">From</label><input id="request-date-from" type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-sm-6 col-lg-2"><label for="request-date-to" class="form-label">To</label><input id="request-date-to" type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div>
<div class="col-sm-6 col-lg-2 d-flex align-items-end"><div class="form-check mb-2"><input id="overdue" name="overdue" value="1" type="checkbox" class="form-check-input" @checked(request()->boolean('overdue'))><label class="form-check-label" for="overdue">Overdue only</label></div></div>
<div class="col-sm-6 col-lg-2 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1">Filter</button><a href="{{ route('admin.requests.index') }}" class="btn btn-outline-secondary">Clear</a></div>
</div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive" tabindex="0" role="region" aria-label="Customer requests"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th scope="col">Request</th><th scope="col">Customer</th><th scope="col">Service</th><th scope="col">Work Progress</th><th scope="col">Source</th><th scope="col">Status</th><th scope="col">Payment</th><th scope="col"><span class="visually-hidden">Actions</span></th></tr></thead><tbody>
@forelse($requests as $item)@php($work=$item->requestServices->where('status','approved')->flatMap->workScopes)@php($resolved=$work->whereIn('status',['completed','not_required','cancelled'])->count())<tr>
<td><strong>{{ $item->reference_no }}</strong>@if($item->file_number)<div class="small text-primary">{{ $item->file_number }}</div>@endif<div class="small text-muted">{{ \App\Support\IndiaDateTime::format($item->created_at, 'd M Y') }}</div></td>
<td><strong>{{ $item->name }}</strong><div class="small text-muted">{{ $item->mobile }}</div></td>
<td>{{ $item->requestServices->pluck('service.name_en')->filter()->implode(', ') ?: $item->service->name_en }}</td>
<td>@if($work->isEmpty())<span class="badge text-bg-secondary">Legacy Workflow</span>@else<strong>{{ $work->where('status','completed')->count() }} / {{ $work->count() }} Completed</strong><div class="small text-muted">{{ $work->where('status','pending')->count() }} Pending · {{ $work->where('status','in_progress')->count() }} In Progress</div><div class="progress mt-1" style="height:5px"><div class="progress-bar" style="width:{{ $work->count()?round($resolved/$work->count()*100):0 }}%"></div></div>@if($item->status==='completed')<span class="badge text-bg-info mt-1">Ready For Dispatch</span>@endif @endif</td>
<td><span class="badge text-bg-{{ $item->isOffline() ? 'secondary' : 'primary' }}">{{ $item->isOffline() ? 'Offline' : 'Online' }}</span></td><td>@include('admin.requests.partials.status-badge',['status'=>$item->lifecycleStatus()])</td><td>@include('admin.requests.partials.payment-badge',['status'=>app(\App\Services\RequestBillingStateResolver::class)->resolve($item)->paymentStatus])</td><td class="text-end"><a href="{{ route('admin.requests.show',$item) }}" class="btn btn-sm btn-outline-primary">Quick View</a></td></tr>
@empty<tr><td colspan="8" class="text-center text-muted py-5">No requests match the selected filters.</td></tr>@endforelse
</tbody></table></div>@if($requests->hasPages())<div class="card-body border-top">{{ $requests->links() }}</div>@endif</div>
@endsection
