@extends('layouts.admin')
@section('title','Customer Requests')
@section('breadcrumbs')<li class="breadcrumb-item active">Requests</li>@endsection
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h2 mb-1">Customer Requests</h1><p class="text-muted mb-0">Search, review and manage submitted requests.</p></div><div class="d-flex align-items-center gap-2"><span class="badge text-bg-primary fs-6">{{ $requests->total() }} requests</span><a href="{{ route('admin.requests.create') }}" class="btn btn-success">Add Offline Request</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form class="card border-0 shadow-sm mb-4" method="GET"><div class="card-body"><div class="row g-3">
    <div class="col-lg-4"><label class="form-label" for="q">Search</label><input id="q" name="q" value="{{ request('q') }}" class="form-control" placeholder="Reference, file, customer or mobile"></div>
    <div class="col-sm-6 col-lg-2"><label class="form-label" for="source">Source</label><select id="source" name="source" class="form-select"><option value="">All</option><option value="online" @selected(request('source')==='online')>Online</option><option value="offline" @selected(request('source')==='offline')>Offline</option></select></div>
    <div class="col-sm-6 col-lg-2"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select"><option value="">All</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></div>
    <div class="col-sm-6 col-lg-2"><label class="form-label" for="payment_status">Payment</label><select id="payment_status" name="payment_status" class="form-select"><option value="">All</option>@foreach(['not_required','pending','received','failed','refunded'] as $status)<option value="{{ $status }}" @selected(request('payment_status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></div>
    <div class="col-sm-6 col-lg-2"><label class="form-label" for="service_id">Service</label><select id="service_id" name="service_id" class="form-select"><option value="">All</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected((string)request('service_id')===(string)$service->id)>{{ $service->name_en }}</option>@endforeach</select></div>
    <div class="col-sm-6 col-lg-2 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1">Filter</button><a href="{{ route('admin.requests.index') }}" class="btn btn-outline-secondary">Clear</a></div>
    <div class="col-sm-6 col-lg-2"><label class="form-label" for="date_from">From</label><input id="date_from" type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="date_to">To</label><input id="date_to" type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div>
</div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Request</th><th>Customer</th><th>Service</th><th>Source</th><th>Submitted</th><th>Status</th><th>Payment</th><th></th></tr></thead><tbody>@forelse($requests as $item)<tr><td><strong>{{ $item->reference_no }}</strong>@if($item->file_number)<div class="small text-primary">{{ $item->file_number }}</div>@endif</td><td><strong>{{ $item->name }}</strong><div class="small text-muted">{{ $item->mobile }}</div></td><td>{{ $item->requestServices->pluck('service.name_en')->filter()->implode(', ') ?: $item->service->name_en }}</td><td><span class="badge text-bg-{{ $item->isOffline() ? 'secondary' : 'primary' }}">{{ $item->isOffline() ? 'Offline' : 'Online' }}</span></td><td>{{ $item->created_at->format('d M Y') }}</td><td>@include('admin.requests.partials.status-badge',['status'=>$item->status])</td><td>@include('admin.requests.partials.payment-badge',['status'=>$item->payment_status])</td><td class="text-end"><a href="{{ route('admin.requests.show',$item) }}" class="btn btn-sm btn-outline-primary">Quick View</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No requests match the selected filters.</td></tr>@endforelse</tbody></table></div>@if($requests->hasPages())<div class="card-body border-top">{{ $requests->links() }}</div>@endif</div>
@endsection
