@extends('layouts.admin')
@section('title','Request '.$customerRequest->reference_no)
@section('breadcrumbs')<li class="breadcrumb-item"><a href="{{ route('admin.requests.index') }}">Requests</a></li><li class="breadcrumb-item active">{{ $customerRequest->reference_no }}</li>@endsection
@section('content')
@if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please correct the action form errors below.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

@include('admin.requests.partials.sticky-action-header')

<div class="accordion request-detail-accordion" id="request-detail-sections">
    <div class="accordion-item" id="section-file"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panel-file" aria-expanded="true" aria-controls="panel-file">1. File Summary</button></h2><div id="panel-file" class="accordion-collapse collapse show" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        <div class="row g-3 mb-4">@foreach([['Reference Number',$customerRequest->reference_no],['File Number',$customerRequest->file_number?:'Not assigned'],['Status',$customerRequest->lifecycleStatus()==='rejected'?'રદ કરેલ / Rejected':str($customerRequest->lifecycleStatus())->headline()],['Payment',str($billingState->paymentStatus)->replace('_',' ')->headline()],['Processing',$processingSummary['percentage'].'%'],['Submitted',$customerRequest->created_at->format('d M Y, g:i A')]] as [$label,$value])<div class="col-6 col-lg-4"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value }}</strong></div>@endforeach</div>
        @unless($customerRequest->usesChecklistWorkflow() || in_array($customerRequest->status,['completed','dispatched','delivered','closed','archived'],true))@include('admin.requests.partials.file-summary')@endunless
        @include('admin.requests.partials.workflow-actions')
        @if($customerRequest->lifecycleStatus() !== 'rejected' && ($customerRequest->assigned_user_id || in_array($billingState->paymentStatus,['paid','not_required'],true)))@include('admin.requests.partials.staff-assignment')@endif
        <div class="mt-4">@include('admin.requests.partials.pdf-downloads')</div>
    </div></div></div>

    <div class="accordion-item" id="section-customer"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-customer" aria-expanded="false" aria-controls="panel-customer">2. Customer Information</button></h2><div id="panel-customer" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">@include('admin.requests.partials.customer-summary-card')</div></div></div>

    <div class="accordion-item" id="section-property"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-property" aria-expanded="false" aria-controls="panel-property">3. Property Information</button></h2><div id="panel-property" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        <div class="row g-3 mb-4">@foreach([['Address',$customerRequest->address?:'Not provided'],['Property Location',collect([$customerRequest->property_village?:$customerRequest->village,$customerRequest->property_taluka?:$customerRequest->taluka,$customerRequest->property_district?:$customerRequest->district])->filter()->implode(', ')?:'Not provided'],['Survey / Block',$customerRequest->survey_numbers?:'—'],['Khata Number',$customerRequest->khata_number?:'—'],['TP Number',$customerRequest->tp_number?:'—'],['Final Plot Number',$customerRequest->final_plot_number?:'—'],['Revenue Village',$customerRequest->revenue_village?:'—'],['Property Remarks',$customerRequest->property_address_remarks?:'—']] as [$label,$value])<div class="col-md-6"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value }}</strong></div>@endforeach</div>
        <h3 class="h6">Private Property Documents</h3><div class="list-group">@forelse($customerRequest->documents as $document)<div class="list-group-item d-flex flex-column flex-md-row justify-content-between gap-2"><div><strong>{{ $document->file_name }}</strong><div class="small text-muted">{{ $document->file_type?:'Unknown type' }} · {{ $document->file_size?number_format($document->file_size/1024,1).' KB':'Unknown size' }} · {{ str($document->source)->title() }}</div></div><a class="btn btn-sm btn-outline-primary align-self-md-center" href="{{ route('admin.requests.documents.download',[$customerRequest,$document]) }}">Secure Download</a></div>@empty<div class="text-muted">No documents uploaded.</div>@endforelse</div>
    </div></div></div>

    <div class="accordion-item" id="section-services"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-services" aria-expanded="false" aria-controls="panel-services">4. Selected Services</button></h2><div id="panel-services" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        <div class="row g-3 mb-4">
            @forelse($customerRequest->requestServices as $selectedService)
                <div class="col-lg-6"><div class="border rounded p-3 h-100"><div class="d-flex justify-content-between gap-2"><strong>{{ $selectedService->service_name_en_snapshot?:$selectedService->service?->name_en }}</strong>@include('admin.requests.partials.status-badge',['status'=>$selectedService->status])</div>@if($selectedService->service_name_gu_snapshot?:$selectedService->service?->name_gu)<div class="small text-muted">{{ $selectedService->service_name_gu_snapshot?:$selectedService->service?->name_gu }}</div>@endif<div class="small mt-2">Professional fee ₹{{ number_format($selectedService->billingProfessionalFee(),2) }} · GST {{ number_format((float)$selectedService->gst_rate,2) }}%</div></div></div>
            @empty
                @if(!$customerRequest->usesChecklistWorkflow() && $customerRequest->service)
                    <div class="col-lg-6"><div class="border rounded p-3 h-100"><strong>{{ $customerRequest->service->name_en }}</strong>@if($customerRequest->service->name_gu)<div class="small text-muted">{{ $customerRequest->service->name_gu }}</div>@endif<div class="small mt-2 text-muted">Historical primary service record</div></div></div>
                @else
                    <div class="text-muted">No selected service snapshots are available.</div>
                @endif
            @endforelse
        </div>
        @if($customerRequest->usesChecklistWorkflow())@include('admin.requests.partials.case-planning')@endif
    </div></div></div>

    <div class="accordion-item" id="section-billing"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-billing" aria-expanded="false" aria-controls="panel-billing">5. Billing Summary</button></h2><div id="panel-billing" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        @include('admin.requests.partials.billing-summary-card')
        @include('admin.requests.partials.approval-pricing')
        <div id="payment-management">@include('admin.requests.partials.payment-management')</div>
    </div></div></div>

    <div class="accordion-item" id="section-checklist"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-checklist" aria-expanded="false" aria-controls="panel-checklist">6. Processing Checklist</button></h2><div id="panel-checklist" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        <div class="row g-3 mb-4"><div class="col-md-3"><small class="text-muted">Overall Progress</small><div class="h3 mb-1">{{ $processingSummary['percentage'] }}%</div><div class="progress" role="progressbar" aria-label="Processing progress" aria-valuenow="{{ $processingSummary['percentage'] }}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:{{ $processingSummary['percentage'] }}%"></div></div></div><div class="col-4 col-md-3"><small class="text-muted d-block">Completed Items</small><strong>{{ $processingSummary['completed'] }}</strong></div><div class="col-4 col-md-3"><small class="text-muted d-block">Remaining Items</small><strong>{{ $processingSummary['remaining'] }}</strong></div><div class="col-4 col-md-3"><small class="text-muted d-block">Current Stage</small><strong>{{ $processingSummary['current_stage'] }}</strong></div></div>
        @include('admin.requests.partials.work-scope-progress')
    </div></div></div>

    <div class="accordion-item" id="section-timeline"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-timeline" aria-expanded="false" aria-controls="panel-timeline">7. Processing Timeline</button></h2><div id="panel-timeline" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        @unless($customerRequest->usesChecklistWorkflow() || in_array($customerRequest->status,['completed','dispatched','delivered','closed','archived'],true))@include('admin.requests.partials.drafting-management') @include('admin.requests.partials.registration-management') @include('admin.requests.partials.post-registration-management')@endunless
        @include('admin.requests.partials.processing-timeline')
    </div></div></div>

    <div class="accordion-item" id="section-dispatch"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-dispatch" aria-expanded="false" aria-controls="panel-dispatch">8. Dispatch</button></h2><div id="panel-dispatch" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        @if($customerRequest->processing?->requires_dispatch ?? $customerRequest->service->requires_dispatch)@include('admin.requests.partials.dispatch-management')@else<div class="alert alert-light border mb-0">Dispatch is not required for this service.</div>@endif
    </div></div></div>

    <div class="accordion-item" id="section-activity"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panel-activity" aria-expanded="false" aria-controls="panel-activity">9. Activity History</button></h2><div id="panel-activity" class="accordion-collapse collapse" data-bs-parent="#request-detail-sections"><div class="accordion-body">
        @include('admin.requests.partials.activity-timeline')
        <hr class="my-4"><div class="row g-4"><div class="col-lg-6"><h3 class="h6">Internal Note</h3><form method="POST" action="{{ route('admin.requests.remarks.store',$customerRequest) }}">@csrf<input type="hidden" name="is_visible_to_customer" value="0"><textarea name="remarks" rows="3" class="form-control mb-2" required placeholder="Admin-only internal note"></textarea><div class="form-text mb-3">Timestamped and never shown in customer tracking or PDFs.</div><button class="btn btn-outline-dark">Add Internal Note</button></form></div><div class="col-lg-6"><h3 class="h6">Customer-visible Remark</h3><form method="POST" action="{{ route('admin.requests.remarks.store',$customerRequest) }}">@csrf<input type="hidden" name="is_visible_to_customer" value="1"><textarea name="remarks" rows="3" class="form-control mb-3" required placeholder="Customer-visible update"></textarea><button class="btn btn-outline-primary">Add Customer Remark</button></form></div></div>
    </div></div></div>
</div>

<div class="modal fade" id="confirmAction" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Confirm action</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body">This action changes the request workflow and will be recorded. Continue?</div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button id="confirm-submit" class="btn btn-primary">Confirm</button></div></div></div></div>
@endsection
@push('styles')<style>.request-action-bar{top:4.5rem;z-index:1010}.request-detail-accordion>.accordion-item{border:0;border-radius:.5rem!important;box-shadow:0 .125rem .25rem rgba(0,0,0,.075);margin-bottom:1rem;overflow:hidden}.request-detail-accordion .accordion-button{font-weight:600;font-size:1.05rem}.request-detail-accordion .accordion-body{padding:1.25rem}@media(max-width:991.98px){.request-action-bar{position:static!important}}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{let form;const modalElement=document.getElementById('confirmAction'),modal=modalElement?new bootstrap.Modal(modalElement):null;document.querySelectorAll('[data-confirm-form]').forEach(item=>item.addEventListener('submit',event=>{if(item.dataset.confirmed||!modal)return;event.preventDefault();form=item;modal.show()}));document.getElementById('confirm-submit')?.addEventListener('click',()=>{if(!form)return;form.dataset.confirmed='1';form.requestSubmit()});document.querySelectorAll('.request-action-bar a[href^="#"]').forEach(link=>link.addEventListener('click',()=>{if(link.classList.contains('disabled'))return;const target=document.querySelector(link.getAttribute('href'));target?.closest('.accordion-collapse')&&bootstrap.Collapse.getOrCreateInstance(target.closest('.accordion-collapse'),{toggle:false}).show()}))});</script>@endpush
