@extends('layouts.admin')
@section('title',$appointment->reference_no)
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h1 class="h3">{{ $appointment->reference_no }}</h1><dl class="row"><dt class="col-4">Customer</dt><dd class="col-8">{{ $appointment->customer_name }}</dd><dt class="col-4">Contact</dt><dd class="col-8">{{ $appointment->mobile }}<br>{{ $appointment->email }}</dd><dt class="col-4">Service</dt><dd class="col-8">{{ $appointment->service->name_en }}</dd><dt class="col-4">Scheduled</dt><dd class="col-8">{{ $appointment->scheduled_at->format('d M Y, g:i A') }}</dd><dt class="col-4">Status</dt><dd class="col-8">{{ $appointment->status->label() }}</dd><dt class="col-4">Purpose</dt><dd class="col-8">{{ $appointment->customer_note ?: '—' }}</dd></dl></div></div>
<div class="card mt-4"><div class="card-body"><h2 class="h5">Activity / History</h2><ul class="list-group list-group-flush">@foreach($appointment->histories as $h)<li class="list-group-item px-0"><strong>{{ ucfirst($h->action) }}</strong> · {{ $h->created_at->format('d M Y H:i') }}<br><small>{{ $h->old_status }} @if($h->new_status)→ {{ $h->new_status }}@endif @if($h->note)· {{ $h->note }}@endif</small></li>@endforeach</ul></div></div></div>
<div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Admin action</h2><form method="POST" action="{{ route('admin.appointments.transition',$appointment) }}">@csrf @method('PATCH')<div class="mb-3"><label class="form-label">Action</label><select class="form-select" name="status" id="status"><option value="confirmed">Confirm</option><option value="rescheduled">Reschedule</option><option value="cancelled">Cancel</option><option value="completed">Complete</option></select></div><div id="reschedule"><div class="mb-3"><label class="form-label">New date</label><input class="form-control" type="date" name="appointment_date"></div><div class="mb-3"><label class="form-label">New time</label><input class="form-control" type="time" step="1800" name="appointment_time"></div></div><div class="mb-3"><label class="form-label">Reason / note</label><textarea class="form-control" name="note" maxlength="1000"></textarea></div><button class="btn btn-primary">Apply action</button></form></div></div></div></div>
@endsection
@push('scripts')<script>const status=document.querySelector('#status'),fields=document.querySelector('#reschedule');function toggle(){fields.hidden=status.value!=='rescheduled'}status.addEventListener('change',toggle);toggle();</script>@endpush
