<!DOCTYPE html><html lang="gu"><head><meta charset="UTF-8"><style>
body{font-family:notosansgujarati,sans-serif;font-size:10pt;line-height:1.45;color:#172033;background:#fff;}h1,h2,h3,p{margin:0}.document-title{font-size:18pt;color:#0b3b82;margin:0 0 4mm}.document-subtitle{color:#65718a;margin-bottom:6mm}.section{margin:0 0 6mm;page-break-inside:auto}.section-title{font-size:11.5pt;color:#0b3b82;border-bottom:1px solid #cfd8e8;padding-bottom:1.5mm;margin-bottom:3mm}.info-table,.data-table{width:100%;border-collapse:collapse}.info-table td{padding:1.7mm 2mm;vertical-align:top;border-bottom:1px solid #edf0f5}.info-table .label{width:29%;color:#667085}.data-table th{background:#eaf0fa;color:#0b3b82;text-align:left;font-weight:bold}.data-table th,.data-table td{border:1px solid #d9dfeb;padding:2mm;vertical-align:top}.data-table tr{page-break-inside:avoid}.text-right{text-align:right}.muted{color:#6b7280}.note{background:#f4f7fb;border-left:3px solid #0b3b82;padding:3mm;margin-top:3mm}.success{background:#edf8f1;border-left-color:#198754}.badge{display:inline-block;padding:1mm 2.5mm;border-radius:2mm;background:#eaf0fa;color:#0b3b82;font-size:8.5pt}.page-break{page-break-before:always}.placeholder-row{margin-top:9mm}.placeholder{display:inline-block;width:44%;height:20mm;border:1px dashed #aab3c2;text-align:center;padding-top:8mm;color:#778195}.placeholder+.placeholder{margin-left:8%}
</style></head><body>
<htmlpageheader name="document-header">@include('pdf.components.header')</htmlpageheader>
<htmlpagefooter name="document-footer">@include('pdf.components.footer')</htmlpagefooter>
<sethtmlpageheader name="document-header" value="on" show-this-page="1"/><sethtmlpagefooter name="document-footer" value="on" show-this-page="1"/>
<h1 class="document-title">{{ $document->type->title() }}</h1><p class="document-subtitle">{{ $document->referenceNumber }}@if($document->fileNumber) &nbsp; | &nbsp; File: {{ $document->fileNumber }}@endif</p>
@yield('pdf-content')
@if($document->company['signature'] || $document->company['stamp'])<table style="width:100%;margin-top:8mm"><tr><td style="width:50%;text-align:center">@if($document->company['signature'])<img src="{{ $document->company['signature'] }}" style="max-width:42mm;max-height:20mm"><div style="font-size:8pt;color:#667085">Authorized Signature</div>@endif</td><td style="width:50%;text-align:center">@if($document->company['stamp'])<img src="{{ $document->company['stamp'] }}" style="max-width:32mm;max-height:24mm"><div style="font-size:8pt;color:#667085">Company Stamp</div>@endif</td></tr></table>@endif
@if($document->showSignaturePlaceholder || $document->showQrPlaceholder)<div class="placeholder-row">@if($document->showSignaturePlaceholder)<div class="placeholder">Digital Signature</div>@endif @if($document->showQrPlaceholder)<div class="placeholder">QR Code</div>@endif</div>@endif
</body></html>
