@extends('pdf.layouts.document')
@section('pdf-content')
@include('pdf.components.customer-summary')
@include('pdf.components.request-summary')
@php($billing=$document->content['billing'])
<div class="section"><h2 class="section-title">Billing Summary / &#xAAC;&#xABF;&#xAB2;&#xAA8;&#xAC0; &#xAB5;&#xABF;&#xA97;&#xAA4;</h2><table class="data-table"><tbody>@foreach([['Original Professional Fee',$billing['original_fee']??null],['Discount',$billing['discount']??null],['Net Professional Fee',$billing['net_fee']??null],['GST ('.number_format($billing['gst_rate']??0,2).'%)',$billing['gst_amount']??null],['Government Charges',$billing['government_charges']??null],['Grand Total',$billing['grand_total']??0],['Amount Paid',$document->content['amount_paid']]] as [$label,$amount])@if($amount!==null)<tr><td>{{ $label }}</td><td class="text-right">INR {{ number_format((float)$amount,2) }}</td></tr>@endif @endforeach<tr><td><strong>Payment Status</strong></td><td class="text-right"><strong>{{ $document->content['payment_status'] }}</strong></td></tr></tbody></table></div>
@if(!empty($billing['charges']))<div class="section"><h2 class="section-title">Government Charge Details</h2><table class="data-table">@foreach($billing['charges'] as $charge)<tr><td>{{ $charge['name'] }}</td><td class="text-right">INR {{ number_format($charge['amount'],2) }}</td></tr>@endforeach</table></div>@endif
<div class="section"><h2 class="section-title">Payment Records / &#xA9A;&#xAC1;&#xA95;&#xAB5;&#xAA3;&#xAC0;</h2><table class="data-table"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Status</th><th class="text-right">Amount</th></tr></thead><tbody>@forelse($document->content['payments'] as $payment)<tr><td>{{ $payment['received_at'] }}</td><td>{{ $payment['method'] }}</td><td>{{ $payment['reference']?:'-' }}</td><td>{{ $payment['status'] }}</td><td class="text-right">INR {{ number_format($payment['amount'],2) }}</td></tr>@if($payment['customer_remark'])<tr><td colspan="5" class="muted">{{ $payment['customer_remark'] }}</td></tr>@endif @empty<tr><td colspan="5" class="muted">No payment records available.</td></tr>@endforelse</tbody></table></div>
@endsection
