@php
    $billing = $customerRequest->billing;
    $approvedServices = $customerRequest->requestServices->where('status', 'approved');
    $allDecided = $customerRequest->requestServices->every(fn ($item) => in_array($item->status, ['approved', 'rejected'], true));
    $rates = $approvedServices->pluck('gst_rate')->map(fn ($rate) => (string) $rate)->unique()->values();
    $defaultGstRate = old('gst_rate', $billing?->gst_rate ?? ($rates->count() === 1 ? $rates->first() : ($rates->first() ?? 0)));
    $allowedCharges = ['Stamp Duty', 'Registration Fee', 'Application Fee', 'Certified Copy Fee', 'Portal Fee', 'Search Fee', 'Other'];
    $defaultCharges = $approvedServices->flatMap(fn ($item) => collect($item->government_charges_snapshot ?? [])->map(fn ($charge, $index) => ['name' => in_array($charge['name'] ?? '', $allowedCharges, true) ? $charge['name'] : 'Other', 'amount' => $charge['amount'] ?? 0, 'note' => in_array($charge['name'] ?? '', $allowedCharges, true) ? ($charge['note'] ?? $charge['description'] ?? null) : trim(($charge['name'] ?? 'Government charge').' '.($charge['note'] ?? $charge['description'] ?? '')), 'display_order' => $index]));
    $chargeRows = old('government_charges', $billing?->charges?->map->only(['name','amount','note','display_order'])->all() ?? $defaultCharges->values()->all());
@endphp
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white"><strong>Service Decisions and Request Billing Summary</strong><div class="small text-muted">Service snapshots remain read-only. One discount and one government-charge section apply to the complete request.</div></div>
    <div class="card-body">
        <h2 class="h6">Selected Services</h2>
        <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Service</th><th class="text-end">Original Professional Fee</th><th class="text-end">GST Snapshot</th><th>Decision</th></tr></thead><tbody>
        @foreach($customerRequest->requestServices as $item)
            <tr><td><strong>{{ $item->service_name_en_snapshot ?: $item->service?->name_en }}</strong><div class="small text-muted">{{ $item->service_name_gu_snapshot ?: $item->service?->name_gu }} · {{ $item->estimated_days ?: '—' }} day(s)</div></td><td class="text-end">₹{{ number_format((float)$item->professional_fee, 2) }}</td><td class="text-end">{{ number_format((float)$item->gst_rate, 2) }}%</td><td style="min-width:240px">@include('admin.requests.partials.status-badge',['status'=>$item->status])
            @unless($billing?->isLocked())<form method="POST" action="{{ route('admin.requests.services.decision', [$customerRequest, $item]) }}" class="d-flex gap-2 mt-2">@csrf @method('PATCH')<input name="decision_notes" class="form-control form-control-sm" placeholder="Optional decision note" value="{{ $item->decision_notes }}"><button name="decision" value="approved" class="btn btn-sm btn-outline-success">Approve</button><button name="decision" value="rejected" class="btn btn-sm btn-outline-danger">Reject</button></form>@endunless</td></tr>
        @endforeach
        </tbody></table></div>

        <hr class="my-4"><h2 class="h5">Request Billing Summary</h2>
        @if($rates->count() > 1)<div class="alert alert-warning py-2">Approved services have different GST snapshots ({{ $rates->implode('%, ') }}%). Confirm the request GST rate before freezing.</div>@endif
        <form method="POST" action="{{ route('admin.requests.billing.finalize', $customerRequest) }}" id="request-billing-form" data-original="{{ $approvedServices->sum('professional_fee') }}">@csrf @method('PATCH')
            <div class="row g-3">
                <div class="col-md-3"><label class="form-label">Total Professional Fee</label><input class="form-control" value="₹{{ number_format((float)$approvedServices->sum('professional_fee'),2) }}" disabled></div>
                <div class="col-md-3"><label class="form-label">Discount Type</label><select name="discount_type" class="form-select" @disabled($billing?->isLocked())>@foreach(['none'=>'None','fixed'=>'Fixed Amount','percentage'=>'Percentage'] as $value=>$label)<option value="{{ $value }}" @selected(old('discount_type',$billing?->discount_type ?? 'none')===$value)>{{ $label }}</option>@endforeach</select></div>
                <div class="col-md-3"><label class="form-label">Discount Value</label><input name="discount_value" type="number" min="0" step="0.01" value="{{ old('discount_value',$billing?->discount_value ?? 0) }}" class="form-control" @disabled($billing?->isLocked())></div>
                <div class="col-md-3"><label class="form-label">GST Rate (%)</label><input name="gst_rate" type="number" min="0" max="100" step="0.01" value="{{ $defaultGstRate }}" class="form-control" required @disabled($billing?->isLocked())></div>
                <div class="col-md-4"><label class="form-label">Discount Reason</label><select name="discount_reason" class="form-select" @disabled($billing?->isLocked())><option value="">Select reason</option>@foreach(['regular_customer'=>'Regular Customer','family'=>'Family','special_discount'=>'Special Discount','festival'=>'Festival','management_approval'=>'Management Approval','other'=>'Other'] as $value=>$label)<option value="{{ $value }}" @selected(old('discount_reason',$billing?->discount_reason)===$value)>{{ $label }}</option>@endforeach</select></div>
                <div class="col-md-8"><label class="form-label">Internal Note</label><input name="internal_note" value="{{ old('internal_note',$billing?->internal_note) }}" class="form-control" maxlength="2000" @disabled($billing?->isLocked())></div>
            </div>
            <h3 class="h6 mt-4">Request-level Government Charges</h3><div id="billing-charge-rows">@foreach($chargeRows as $index=>$charge)<div class="row g-2 mb-2 billing-charge-row"><div class="col-md-3"><select name="government_charges[{{ $index }}][name]" class="form-select" @disabled($billing?->isLocked())>@foreach($allowedCharges as $name)<option @selected(($charge['name'] ?? '')===$name)>{{ $name }}</option>@endforeach</select></div><div class="col-md-2"><input name="government_charges[{{ $index }}][amount]" value="{{ $charge['amount'] ?? 0 }}" type="number" min="0" step="0.01" class="form-control charge-amount" @disabled($billing?->isLocked())></div><div class="col-md-4"><input name="government_charges[{{ $index }}][note]" value="{{ $charge['note'] ?? '' }}" class="form-control" placeholder="Optional note" @disabled($billing?->isLocked())></div><div class="col-md-2"><input name="government_charges[{{ $index }}][display_order]" value="{{ $charge['display_order'] ?? $index }}" type="number" min="0" class="form-control" @disabled($billing?->isLocked())></div><div class="col-md-1">@unless($billing?->isLocked())<button type="button" class="btn btn-outline-danger remove-billing-charge">×</button>@endunless</div></div>@endforeach</div>
            @unless($billing?->isLocked())<button type="button" id="add-billing-charge" class="btn btn-sm btn-outline-primary">Add Government Charge</button>@endunless
            <div class="table-responsive mt-4"><table class="table"><tbody><tr><th>Total Original Professional Fee</th><td class="text-end" id="bill-original">₹0.00</td></tr><tr><th>Discount Amount</th><td class="text-end" id="bill-discount">₹0.00</td></tr><tr><th>Net Professional Fee</th><td class="text-end" id="bill-net">₹0.00</td></tr><tr><th>GST</th><td class="text-end" id="bill-gst">₹0.00</td></tr><tr><th>Government Charges Total</th><td class="text-end" id="bill-government">₹0.00</td></tr><tr class="table-primary"><th>Grand Total</th><th class="text-end" id="bill-grand">₹0.00</th></tr></tbody></table></div>
            @unless($billing?->isLocked())<button class="btn btn-success" @disabled(!$allDecided || $approvedServices->isEmpty())>Approve & Freeze Request Billing</button>@endunless
        </form>
        @if($billing?->isLocked())<div class="alert alert-success">Pricing frozen {{ $billing->applied_at?->format('d M Y, g:i A') }} by {{ $billing->appliedBy?->name ?? 'System' }}.</div><form method="POST" action="{{ route('admin.requests.billing.unlock',$customerRequest) }}">@csrf @method('PATCH')<label class="form-label">Explicit unlock reason</label><div class="input-group"><input name="unlock_reason" class="form-control" required maxlength="1000"><button class="btn btn-outline-warning">Unlock Pricing</button></div></form>@endif
        @if($billing?->history?->isNotEmpty())<details class="mt-3"><summary>Billing audit history</summary><ul class="small mt-2">@foreach($billing->history as $entry)<li>{{ str($entry->action)->headline() }} by {{ $entry->changedBy?->name ?? 'System' }} on {{ $entry->created_at->format('d M Y, g:i A') }} — ₹{{ number_format((float)($entry->pricing_snapshot['grand_total'] ?? 0),2) }}@if($entry->reason) — {{ $entry->reason }}@endif</li>@endforeach</ul></details>@endif
    </div>
</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('request-billing-form');if(!form)return;const money=v=>'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}),calc=()=>{const original=+form.dataset.original||0,type=form.elements.discount_type?.value||'none',value=+form.elements.discount_value?.value||0,discount=type==='fixed'?value:type==='percentage'?original*value/100:0,net=Math.max(0,original-discount),gst=net*(+form.elements.gst_rate?.value||0)/100,government=[...form.querySelectorAll('.charge-amount')].reduce((sum,input)=>sum+(+input.value||0),0);document.getElementById('bill-original').textContent=money(original);document.getElementById('bill-discount').textContent=money(discount);document.getElementById('bill-net').textContent=money(net);document.getElementById('bill-gst').textContent=money(gst);document.getElementById('bill-government').textContent=money(government);document.getElementById('bill-grand').textContent=money(net+gst+government)};form.addEventListener('input',calc);document.getElementById('billing-charge-rows')?.addEventListener('click',event=>{if(event.target.matches('.remove-billing-charge')){event.target.closest('.billing-charge-row').remove();calc()}});document.getElementById('add-billing-charge')?.addEventListener('click',()=>{const rows=document.getElementById('billing-charge-rows'),index=rows.querySelectorAll('.billing-charge-row').length,row=document.createElement('div');row.className='row g-2 mb-2 billing-charge-row';row.innerHTML=`<div class="col-md-3"><select name="government_charges[${index}][name]" class="form-select">${['Stamp Duty','Registration Fee','Application Fee','Certified Copy Fee','Portal Fee','Search Fee','Other'].map(v=>`<option>${v}</option>`).join('')}</select></div><div class="col-md-2"><input name="government_charges[${index}][amount]" type="number" min="0" step="0.01" class="form-control charge-amount" value="0"></div><div class="col-md-4"><input name="government_charges[${index}][note]" class="form-control" placeholder="Optional note"></div><div class="col-md-2"><input name="government_charges[${index}][display_order]" type="number" min="0" class="form-control" value="${index}"></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-billing-charge">×</button></div>`;rows.append(row)});calc()});</script>@endpush