<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white"><strong>Approval & Payment Finalization</strong><div class="small text-muted">Changes apply only to this request. Service Master values are never modified.</div></div>
    <div class="card-body"><div class="accordion" id="pricing-accordion">
    @foreach($customerRequest->requestServices as $selectedService)
        @php($charges = old('government_charges', $selectedService->government_charges_snapshot ?? []))
        <div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" data-bs-toggle="collapse" data-bs-target="#pricing-{{ $selectedService->id }}" type="button"><span class="me-2">{{ $selectedService->service->name_en }}</span>@if($selectedService->pricing_locked_at)<span class="badge text-bg-success">Pricing Locked</span>@endif</button></h2>
        <div id="pricing-{{ $selectedService->id }}" class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}" data-bs-parent="#pricing-accordion"><div class="accordion-body">
        <form method="POST" action="{{ route('admin.requests.services.decision',[$customerRequest,$selectedService]) }}" class="pricing-form" data-original="{{ $selectedService->original_professional_fee ?? $selectedService->professional_fee }}" data-gst="{{ $selectedService->gst_rate }}">@csrf @method('PATCH')
            <input type="hidden" name="decision" value="approved">
            <div class="row g-3"><div class="col-md-3"><label class="form-label">Original Professional Fee</label><input class="form-control" value="₹{{ number_format((float)($selectedService->original_professional_fee ?? $selectedService->professional_fee),2) }}" disabled></div>
            <div class="col-md-3"><label class="form-label">Discount Type</label><select name="discount_type" class="form-select discount-type"><option value="none">None</option><option value="fixed">Fixed Amount</option><option value="percentage">Percentage</option></select></div>
            <div class="col-md-3"><label class="form-label">Discount Value</label><input name="discount_value" type="number" min="0" step="0.01" value="{{ $selectedService->discount_value ?? 0 }}" class="form-control discount-value"></div>
            <div class="col-md-3"><label class="form-label">Discount Reason</label><select name="discount_reason" class="form-select"><option value="">Select reason</option>@foreach(['regular_customer'=>'Regular Customer','family'=>'Family','special_discount'=>'Special Discount','festival'=>'Festival','management_approval'=>'Management Approval','other'=>'Other'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div></div>
            <h3 class="h6 mt-4">Government Charges</h3><div class="charge-rows">@foreach($charges as $index=>$charge)<div class="row g-2 mb-2 charge-row"><div class="col-md-4"><input name="government_charges[{{ $index }}][name]" value="{{ $charge['name'] ?? '' }}" class="form-control" placeholder="Charge name" required></div><div class="col-md-3"><input name="government_charges[{{ $index }}][amount]" value="{{ $charge['amount'] ?? 0 }}" type="number" min="0" step="0.01" class="form-control charge-amount" required></div><div class="col-md-4"><input name="government_charges[{{ $index }}][note]" value="{{ $charge['note'] ?? $charge['description'] ?? '' }}" class="form-control" placeholder="Optional note"></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-charge">×</button></div></div>@endforeach</div>
            <button type="button" class="btn btn-sm btn-outline-primary add-charge">Add Charge</button>
            <div class="table-responsive mt-4"><table class="table table-sm"><tbody><tr><th>Net Professional Fee</th><td class="text-end net-fee">₹0.00</td></tr><tr><th>GST ({{ number_format((float)$selectedService->gst_rate,2) }}%)</th><td class="text-end gst-amount">₹0.00</td></tr><tr><th>Government Charges</th><td class="text-end government-total">₹0.00</td></tr><tr class="table-primary"><th>Total Payable</th><th class="text-end final-total">₹0.00</th></tr></tbody></table></div>
            <label class="form-label">Internal decision note</label><textarea name="decision_notes" class="form-control mb-3" rows="2"></textarea>
            <button class="btn btn-success" @disabled($selectedService->pricing_locked_at && !$selectedService->pricing_unlocked_at)>Approve & Freeze Payment Summary</button>
        </form>
        @if($selectedService->pricing_locked_at)<form method="POST" action="{{ route('admin.requests.services.pricing.unlock',[$customerRequest,$selectedService]) }}" class="border-top mt-3 pt-3">@csrf @method('PATCH')<label class="form-label">Explicit unlock reason</label><div class="input-group"><input name="unlock_note" class="form-control" required><button class="btn btn-outline-warning">Unlock Pricing</button></div></form>@endif
        @if($selectedService->approvalHistory->isNotEmpty())<details class="mt-3"><summary>Approval history</summary><ul class="small mt-2">@foreach($selectedService->approvalHistory as $entry)<li>{{ str($entry->action)->headline() }} by {{ $entry->approvedBy?->name ?? 'System' }} on {{ $entry->created_at->format('d M Y, g:i A') }} — ₹{{ number_format((float)($entry->pricing_snapshot['final_total'] ?? 0),2) }}</li>@endforeach</ul></details>@endif
        </div></div></div>
    @endforeach
    </div></div>
</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const money=v=>'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});document.querySelectorAll('.pricing-form').forEach(form=>{const calculate=()=>{const original=+form.dataset.original,type=form.querySelector('.discount-type').value,value=+form.querySelector('.discount-value').value||0,discount=type==='fixed'?value:type==='percentage'?original*value/100:0,net=Math.max(0,original-discount),gst=net*(+form.dataset.gst)/100,government=[...form.querySelectorAll('.charge-amount')].reduce((sum,input)=>sum+(+input.value||0),0);form.querySelector('.net-fee').textContent=money(net);form.querySelector('.gst-amount').textContent=money(gst);form.querySelector('.government-total').textContent=money(government);form.querySelector('.final-total').textContent=money(net+gst+government)};form.addEventListener('input',calculate);form.addEventListener('click',event=>{if(event.target.matches('.remove-charge')){event.target.closest('.charge-row').remove();calculate()}if(event.target.matches('.add-charge')){const index=form.querySelectorAll('.charge-row').length,row=document.createElement('div');row.className='row g-2 mb-2 charge-row';row.innerHTML=`<div class="col-md-4"><input name="government_charges[${index}][name]" class="form-control" placeholder="Charge name" required></div><div class="col-md-3"><input name="government_charges[${index}][amount]" type="number" min="0" step="0.01" class="form-control charge-amount" required></div><div class="col-md-4"><input name="government_charges[${index}][note]" class="form-control" placeholder="Optional note"></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-charge">×</button></div>`;form.querySelector('.charge-rows').append(row)}});calculate()})});</script>@endpush
