@php($caseLocked = $billingState->pricingLocked || in_array($customerRequest->status, ['completed','dispatched','delivered','closed','archived'], true))
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Case Planning & Approval</h2></div><div class="card-body">
<div class="row g-3 mb-4">@foreach([['Reference Number',$customerRequest->reference_no],['Customer',$customerRequest->name],['Mobile',$customerRequest->mobile],['Request Source',$customerRequest->isOffline()?'Offline':'Online'],['Selected Services',$customerRequest->requestServices->count()],['Current Status',str($customerRequest->status)->headline()],['Payment Status',str($billingState->paymentStatus)->replace('_',' ')->headline()],['File Number',$customerRequest->file_number ?: 'Not assigned']] as [$label,$value])<div class="col-6 col-lg-3"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value }}</strong></div>@endforeach</div>
@if($caseLocked)<div class="alert alert-secondary mb-0">Case Planning and normal processing are locked because this case is completed or closed. Dispatch / Delivery management remains available.</div>@else
<form method="POST" action="{{ route('admin.requests.case-planning.save',$customerRequest) }}">@csrf @method('PATCH')<div class="accordion" id="case-services">
@foreach($customerRequest->requestServices as $selectedService)
@php($savedScopes=$selectedService->workScopes)
@php($suggested=$savedScopes->isNotEmpty() ? $savedScopes->whereNotNull('work_scope_item_id')->pluck('work_scope_item_id')->all() : $selectedService->service->defaultWorkScopes->pluck('id')->all())
@php($decision=old("services.{$selectedService->id}.decision",in_array($selectedService->status,['approved','rejected','under_review'],true)?$selectedService->status:'under_review'))
<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button {{ $loop->first?'':'collapsed' }}" type="button" data-bs-toggle="collapse" data-bs-target="#case-service-{{ $selectedService->id }}"><span><strong>{{ $selectedService->service_name_en_snapshot ?: $selectedService->service->name_en }}</strong><small class="d-block text-muted">{{ $selectedService->service_name_gu_snapshot ?: $selectedService->service->name_gu }} · Fee ₹{{ number_format((float)$selectedService->professional_fee,2) }}</small></span></button></h3><div id="case-service-{{ $selectedService->id }}" class="accordion-collapse collapse {{ $loop->first?'show':'' }}" data-bs-parent="#case-services"><div class="accordion-body">
<div class="row g-3"><div class="col-md-4"><label class="form-label">Decision</label><select name="services[{{ $selectedService->id }}][decision]" class="form-select" required><option value="under_review" @selected($decision==='under_review')>Keep Under Review</option><option value="approved" @selected($decision==='approved')>Accept</option><option value="rejected" @selected($decision==='rejected')>Reject</option></select></div><div class="col-md-8"><label class="form-label">Decision / Rejection Note</label><textarea name="services[{{ $selectedService->id }}][decision_notes]" class="form-control" rows="2">{{ old("services.{$selectedService->id}.decision_notes",$selectedService->decision_notes) }}</textarea><div class="form-text">Required when rejected. Internal only.</div></div></div>
<div class="mt-3"><label class="form-label">Customer-visible decision message (optional)</label><input name="services[{{ $selectedService->id }}][customer_decision_message]" value="{{ old("services.{$selectedService->id}.customer_decision_message",$selectedService->customer_decision_message) }}" class="form-control" maxlength="500"></div>
<div class="mt-4"><h4 class="h6">Included Work Scope</h4><div class="row g-2">@foreach($workScopeItems as $scope)@php($saved=$savedScopes->firstWhere('work_scope_item_id',$scope->id))<div class="col-md-6"><div class="border rounded p-2 h-100"><label class="form-check"><input class="form-check-input" type="checkbox" name="services[{{ $selectedService->id }}][work_scope_ids][]" value="{{ $scope->id }}" @checked(in_array($scope->id,old("services.{$selectedService->id}.work_scope_ids",$suggested),true))><span class="form-check-label"><strong>{{ $scope->name_en }}</strong><small class="d-block text-muted">{{ $scope->name_gu }}</small></span></label>@if($saved)<select name="services[{{ $selectedService->id }}][scope_statuses][{{ $scope->id }}]" class="form-select form-select-sm mt-2">@foreach(['pending'=>'Pending','in_progress'=>'In Progress','completed'=>'Completed','cancelled'=>'Cancelled / Not Required'] as $value=>$label)<option value="{{ $value }}" @selected($saved->status===$value)>{{ $label }}</option>@endforeach</select>@endif</div></div>@endforeach</div></div>
<div class="row g-3 mt-2"><div class="col-md-6"><label class="form-label">Custom work item (optional)</label><input name="services[{{ $selectedService->id }}][custom_work_item]" value="{{ old("services.{$selectedService->id}.custom_work_item",$savedScopes->firstWhere('is_custom',true)?->name_en_snapshot) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Internal scope note</label><input name="services[{{ $selectedService->id }}][internal_note]" value="{{ old("services.{$selectedService->id}.internal_note",$savedScopes->first()?->internal_note) }}" class="form-control"></div></div>
</div></div></div>@endforeach</div><button class="btn btn-primary mt-3">Save Case Planning</button></form>
@if($availableServices->isNotEmpty())<form method="POST" action="{{ route('admin.requests.services.add',$customerRequest) }}" class="border rounded p-3 mt-3" id="add-request-service-form">@csrf<h3 class="h6">Add Service</h3><div class="row g-3"><div class="col-lg-6"><label class="form-label" for="add-service-id">Service</label><select id="add-service-id" name="service_id" class="form-select @error('service_id') is-invalid @enderror" required><option value="">Select an active service…</option>@foreach($availableServices as $service)<option value="{{ $service->id }}" data-default-fee="{{ number_format((float)($service->service_fee ?? 0),2,'.','') }}" data-gst-rate="{{ number_format((float)($service->gst_rate ?? 0),2,'.','') }}" data-estimated-days="{{ $service->estimated_days ?? '' }}" @selected((int)old('service_id')===$service->id)>{{ $service->name_en }} / {{ $service->name_gu }}</option>@endforeach</select>@error('service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 col-lg-2"><label class="form-label">Default Fee</label><input id="add-service-default-fee" class="form-control" value="" disabled></div><div class="col-md-4 col-lg-2"><label class="form-label" for="add-service-request-fee">Fee for this Request</label><input id="add-service-request-fee" name="professional_fee" type="number" min="0" step="0.01" value="{{ old('professional_fee') }}" class="form-control @error('professional_fee') is-invalid @enderror" required>@error('professional_fee')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 col-lg-2"><label class="form-label">GST Rate</label><input id="add-service-gst-rate" class="form-control" value="" disabled></div><div class="col-md-4"><label class="form-label">Estimated Days</label><input id="add-service-estimated-days" class="form-control" value="" disabled></div><div class="col-md-8"><label class="form-label" for="add-service-note">Internal Note <span class="text-muted">(optional)</span></label><input id="add-service-note" name="internal_note" value="{{ old('internal_note') }}" maxlength="2000" class="form-control @error('internal_note') is-invalid @enderror">@error('internal_note')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><button class="btn btn-outline-primary">Add to Same Request</button></div></div></form>@endif
<form method="POST" action="{{ route('admin.requests.case-planning.reject',$customerRequest) }}" class="mt-2">@csrf @method('PATCH')<button class="btn btn-outline-danger btn-sm">Reject Case (all services rejected)</button></form>@endif
</div></div>
@if(!$caseLocked && $customerRequest->requestServices->where('status','approved')->isNotEmpty())<form method="POST" action="{{ route('admin.requests.case-planning.complete',$customerRequest) }}" class="card border-0 shadow-sm mb-4">@csrf @method('PATCH')<div class="card-body"><h2 class="h6">Completion</h2><p class="small text-muted">Available after every included work item is Completed or Cancelled / Not Required.</p><input name="remarks" class="form-control mb-2" placeholder="Completion note (optional)"><button class="btn btn-success">Mark Request Completed</button></div></form>@endif
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{[...document.querySelectorAll('.card-header')].find(h=>h.textContent.trim()==='Selected Services')?.closest('.card')?.remove();document.querySelectorAll('select[name*="[scope_statuses]"]').forEach(select=>select.remove());if(document.getElementById('processing-checklist')&&!document.querySelector('#processing-checklist .badge.text-bg-secondary')){[...document.querySelectorAll('h2.h6')].find(h=>h.textContent.trim()==='Completion')?.closest('form')?.remove()}const select=document.getElementById('add-service-id');const requestFee=document.getElementById('add-service-request-fee');const sync=()=>{if(!select)return;const option=select.selectedOptions[0];document.getElementById('add-service-default-fee').value=option?.dataset.defaultFee?`₹${option.dataset.defaultFee}`:'';document.getElementById('add-service-gst-rate').value=option?.dataset.gstRate?`${option.dataset.gstRate}%`:'';document.getElementById('add-service-estimated-days').value=option?.dataset.estimatedDays||'After review';if(requestFee&&!requestFee.dataset.edited)requestFee.value=option?.dataset.defaultFee||''};requestFee?.addEventListener('input',()=>requestFee.dataset.edited='1');select?.addEventListener('change',()=>{if(requestFee)delete requestFee.dataset.edited;sync()});sync()});</script>@endpush
