@php
    $paymentEligibleStatuses = ['approved','payment_pending','payment_received','draft_in_progress','ready_for_verification','customer_approved','ready_for_registration','dispatched','completed','archived'];
    $paymentEligible = $customerRequest->file_number && in_array($customerRequest->status, $paymentEligibleStatuses, true);
    $acceptedServiceFee = $customerRequest->requestServices->where('status', 'approved')->sum(fn ($service) => $service->billingProfessionalFee());
    $payableAmount = (float) ($customerRequest->billing?->grand_total ?? $customerRequest->amount_due);
    $invalidFrozenBilling = $acceptedServiceFee > 0 && $payableAmount <= 0;
    $paymentEligible = $paymentEligible && ! $invalidFrozenBilling;
    $methods = $customerRequest->isOffline() ? ['upi','bank_transfer','cheque','cash','other'] : ['upi','bank_transfer','other'];
@endphp
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white d-flex justify-content-between align-items-center"><span class="fw-semibold">Payment Management</span><span class="badge text-bg-{{ $customerRequest->isOffline() ? 'secondary' : 'primary' }}">{{ $customerRequest->isOffline() ? 'Offline / Walk-in' : 'Online / Public' }}</span></div>
    <div class="card-body">
        <div class="row g-3 mb-4"><div class="col-6"><small class="text-muted">Frozen Billing Total</small><div class="h5 mb-0">₹{{ number_format($payableAmount,2) }}</div></div><div class="col-6"><small class="text-muted">Paid Amount</small><div class="h5 mb-0">₹{{ number_format((float)$customerRequest->amount_paid,2) }}</div></div></div>
        @error('payment')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror
        @if($invalidFrozenBilling)<div class="alert alert-danger" role="alert">Payment cannot be recorded because the frozen billing Grand Total is zero while an accepted service has a professional fee. Approve and freeze the request billing again.</div>
        @elseif($paymentEligible && !$customerRequest->billing)
            <form method="POST" action="{{ route('admin.requests.fee.update',$customerRequest) }}" class="border-top pt-3">@csrf @method('PATCH')<label class="form-label" for="final_fee">Final Service Fee</label><div class="input-group"><span class="input-group-text">₹</span><input id="final_fee" name="final_fee" type="number" min="0" max="99999999.99" step="0.01" value="{{ old('final_fee',$customerRequest->amount_due) }}" class="form-control @error('final_fee') is-invalid @enderror" required><button class="btn btn-outline-primary">Update Fee</button>@error('final_fee')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></form>
        @elseif(!$paymentEligible)<div class="alert alert-light border mb-0">Payment actions become available only after approval and file-number assignment.</div>@endif
        @if($customerRequest->fee_updated_at)<div class="small text-muted mt-2">Fee last updated {{ $customerRequest->fee_updated_at->format('d M Y, g:i A') }} by {{ $customerRequest->feeUpdatedBy?->name ?? 'System' }}.</div>@endif
    </div>
</div>
@if($customerRequest->payments->isNotEmpty())<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Payment History</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>Date</th><th>Status</th><th>Amount</th><th>Method</th><th>Reference</th><th>Recorded By</th></tr></thead><tbody>@foreach($customerRequest->payments as $payment)<tr><td>{{ $payment->received_at->format('d M Y') }}</td><td>@include('admin.requests.partials.payment-badge',['status'=>$payment->payment_status])</td><td>₹{{ number_format((float)$payment->amount,2) }}</td><td>{{ str($payment->payment_method)->replace('_',' ')->title() }}</td><td>{{ $payment->transaction_reference ?: '—' }}</td><td>{{ $payment->receivedBy?->name ?? 'System' }}</td></tr>@if($payment->notes || $payment->customer_remark)<tr class="table-light"><td></td><td colspan="5"><small>@if($payment->notes)<strong>Internal:</strong> {{ $payment->notes }} @endif @if($payment->customer_remark)<strong class="ms-2">Customer visible:</strong> {{ $payment->customer_remark }}@endif</small></td></tr>@endif @endforeach</tbody></table></div></div>@endif
@if($paymentEligible)<div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Add Payment / Update Payment</div><div class="card-body"><form method="POST" action="{{ route('admin.requests.payments.store',$customerRequest) }}" data-confirm-form>@csrf<div class="row g-3"><div class="col-sm-6"><label class="form-label">Status</label><select name="payment_status" class="form-select" required>@foreach(['pending','received','failed','refunded'] as $status)<option value="{{ $status }}">{{ str($status)->title() }}</option>@endforeach</select></div><div class="col-sm-6"><label class="form-label">Amount</label><input type="number" step="0.01" min="0.01" max="99999999.99" name="amount" value="{{ old('amount') }}" class="form-control" required></div><div class="col-sm-6"><label class="form-label">Method</label><select name="payment_method" class="form-select" required>@foreach($methods as $method)<option value="{{ $method }}">{{ str($method)->replace('_',' ')->title() }}</option>@endforeach</select>@unless($customerRequest->isOffline())<div class="form-text">Cash and cheque are not permitted for online requests.</div>@endunless</div><div class="col-sm-6"><label class="form-label">Payment Date</label><input type="datetime-local" name="received_at" value="{{ old('received_at',now()->format('Y-m-d\TH:i')) }}" class="form-control" required></div><div class="col-12"><label class="form-label">Transaction / Reference Number <span class="text-muted">(optional)</span></label><input name="transaction_reference" value="{{ old('transaction_reference') }}" class="form-control"></div><div class="col-12"><label class="form-label">Internal Admin Note</label><textarea name="notes" class="form-control" rows="2">{{ old('notes') }}</textarea><div class="form-text">Never visible to the customer.</div></div><div class="col-12"><label class="form-label">Customer-visible Payment Remark <span class="text-muted">(optional)</span></label><textarea name="customer_remark" class="form-control" rows="2">{{ old('customer_remark') }}</textarea></div></div><button class="btn btn-success w-100 mt-3">Save Payment Record</button></form></div></div>@endif
