@php
$accepted=$customerRequest->requestServices->where('status','approved'); $scopes=$accepted->flatMap->workScopes; $completed=$scopes->where('status','completed')->count(); $resolved=$scopes->whereIn('status',['completed','not_required','cancelled'])->count(); $pending=$scopes->where('status','pending')->count(); $inProgress=$scopes->where('status','in_progress')->count(); $percent=$scopes->count()?(int)round($resolved/$scopes->count()*100):0; $locked=in_array($customerRequest->status,['completed','dispatched','delivered','closed','archived'],true); $labels=['pending'=>'Pending','in_progress'=>'In Progress','completed'=>'Completed','not_required'=>'Not Required','cancelled'=>'Cancelled']; $colors=['pending'=>'secondary','in_progress'=>'primary','completed'=>'success','not_required'=>'warning','cancelled'=>'danger'];
@endphp
<section class="card border-0 shadow-sm mb-4" id="processing-checklist"><div class="card-body">
<div class="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><h2 class="h4 mb-1">Processing &amp; Work Checklist</h2><p class="text-muted mb-0">Work selected during approved Case Planning only.</p></div>@if(!$customerRequest->usesChecklistWorkflow())<span class="badge text-bg-secondary">Legacy Workflow</span>@endif</div>
@if($customerRequest->usesChecklistWorkflow())<div class="row g-3 mb-4" aria-label="Checklist groups">@foreach($checklistGroups as $group=>$items)<div class="col-sm-6 col-xl-3"><div class="border rounded p-3 h-100"><div class="d-flex justify-content-between gap-2"><strong>{{ $group }}</strong><span class="badge text-bg-light border">{{ $items->count() }}</span></div>@forelse($items as $item)<div class="small mt-2 d-flex justify-content-between gap-2"><span>{{ $item->name_en_snapshot }}</span><span class="text-muted">{{ str($item->status)->headline() }}</span></div>@empty<div class="small text-muted mt-2">No selected items</div>@endforelse</div></div>@endforeach</div>@endif
@if(!$customerRequest->usesChecklistWorkflow())<div class="alert alert-secondary mb-0">This historical request uses the legacy processing record. Its stage history remains readable above; new processing actions are not driven by those stages.</div>
@else
<div class="row g-3 mb-4"><div class="col-lg-5"><div class="border rounded p-3 h-100"><div class="d-flex justify-content-between"><strong>Progress</strong><strong>{{ $completed }} of {{ $scopes->count() }} completed</strong></div><div class="progress mt-3" style="height:10px"><div class="progress-bar" style="width:{{ $percent }}%"></div></div><small class="text-muted d-block mt-2">{{ $resolved }} of {{ $scopes->count() }} resolved</small></div></div>@foreach([['Pending',$pending,'secondary'],['In Progress',$inProgress,'primary'],['Completed',$completed,'success']] as [$label,$count,$color])<div class="col-4 col-lg"><div class="border rounded p-3 text-center h-100"><span class="badge text-bg-{{ $color }}">{{ $label }}</span><div class="fs-4 fw-bold mt-2">{{ $count }}</div></div></div>@endforeach</div>
@if($processingEligibility['payment_pending'])<div class="alert alert-warning"><strong>Payment Pending.</strong> Payment must be confirmed before processing can start.</div>@elseif(!$processingEligibility['eligible'])<div class="alert alert-warning"><strong>Processing unavailable.</strong><ul class="mb-0">@foreach($processingEligibility['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul></div>@endif
@if($locked)<div class="alert alert-{{ $customerRequest->status==='completed'?'success':'secondary' }}">{{ $customerRequest->status==='completed'?'Case processing is complete. Add dispatch or delivery details.':'Processing is read-only because the case is '.str($customerRequest->status)->headline().'.' }}</div>@endif
@if($customerRequest->status==='completed')<form method="POST" action="{{ route('admin.requests.processing.reopen',$customerRequest) }}" class="row g-2 mb-4">@csrf @method('PATCH')<div class="col-md-9"><input name="reason" class="form-control" required placeholder="Required case reopen reason"></div><div class="col-md-3"><button class="btn btn-outline-danger w-100">Reopen Case</button></div></form>@endif
@unless($locked)<form id="bulk-progress-form" method="POST" action="{{ route('admin.requests.processing.work-items.bulk',$customerRequest) }}" class="border rounded p-3 mb-4">@csrf @method('PATCH')<h3 class="h6">Selected Work Actions</h3><div class="row g-2 mb-3"><div class="col-md-4"><input name="reason" class="form-control" placeholder="Reason for Not Required / Cancelled"></div><div class="col-md-4"><input name="internal_note" class="form-control" placeholder="Common internal note"></div><div class="col-md-4"><input name="customer_remark" class="form-control" placeholder="Common customer-visible remark"></div></div><div class="d-flex flex-wrap gap-2"><button name="action" value="start_selected" class="btn btn-outline-primary">Start Selected</button><button name="action" value="complete_selected" class="btn btn-outline-success">Complete Selected</button><button name="action" value="not_required" class="btn btn-outline-warning">Mark Not Required</button><button name="action" value="cancel_selected" class="btn btn-outline-danger">Cancel Selected</button><button name="action" value="save_notes" class="btn btn-outline-secondary">Save Notes</button></div></form>@endunless
@foreach($accepted as $selectedService)<div class="mb-4"><h3 class="h5 border-bottom pb-2">{{ $selectedService->service_name_en_snapshot?:$selectedService->service->name_en }}@if($selectedService->service_name_gu_snapshot)<small class="text-muted"> / {{ $selectedService->service_name_gu_snapshot }}</small>@endif</h3><div class="row g-3">@foreach($selectedService->workScopes as $scope)<div class="col-xl-6"><article class="border rounded p-3 h-100">
<div class="d-flex gap-3 align-items-start mb-3">@unless($locked)<input form="bulk-progress-form" class="form-check-input mt-1" type="checkbox" name="work_scope_ids[]" value="{{ $scope->id }}">@endunless<div class="flex-grow-1"><h4 class="h6 mb-1">{{ $scope->name_en_snapshot }}</h4>@if($scope->name_gu_snapshot)<div class="small text-muted">{{ $scope->name_gu_snapshot }}</div>@endif</div><span class="badge text-bg-{{ $colors[$scope->status]??'secondary' }}">{{ $labels[$scope->status]??str($scope->status)->headline() }}</span></div>
<dl class="row small mb-3"><dt class="col-5 text-muted">Started Date</dt><dd class="col-7">{{ $scope->started_at ? \App\Support\IndiaDateTime::format($scope->started_at).' IST' : '—' }}</dd><dt class="col-5 text-muted">Completed Date</dt><dd class="col-7">{{ $scope->completed_at ? \App\Support\IndiaDateTime::format($scope->completed_at).' IST' : '—' }}</dd><dt class="col-5 text-muted">Assigned Admin</dt><dd class="col-7">{{ $scope->updatedBy?->name?:'Not assigned' }}</dd><dt class="col-5 text-muted">Internal Note</dt><dd class="col-7">{{ $scope->internal_note?:'—' }}</dd><dt class="col-5 text-muted">Customer Remark</dt><dd class="col-7">{{ $scope->customer_remark?:'—' }}</dd>@if($scope->resolution_reason)<dt class="col-5 text-muted">Resolution Reason</dt><dd class="col-7">{{ $scope->resolution_reason }}</dd>@endif</dl>
@unless($locked)@if($scope->status==='completed')<form method="POST" action="{{ route('admin.requests.processing.work-items.reopen',[$customerRequest,$scope]) }}" class="row g-2">@csrf @method('PATCH')<div class="col"><input name="reason" required class="form-control form-control-sm" placeholder="Required reopen reason"></div><div class="col-auto"><button class="btn btn-sm btn-outline-danger">Reopen</button></div></form>@else<form method="POST" action="{{ route('admin.requests.processing.work-items.update',[$customerRequest,$scope]) }}">@csrf @method('PATCH')<div class="row g-2"><div class="col-md-4"><select name="status" class="form-select form-select-sm">@if($scope->status==='pending')<option value="pending">Pending</option><option value="in_progress">In Progress</option><option value="not_required">Not Required</option><option value="cancelled">Cancelled</option>@elseif($scope->status==='in_progress')<option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="not_required">Not Required</option><option value="cancelled">Cancelled</option>@else<option value="{{ $scope->status }}">{{ $labels[$scope->status] }}</option>@endif</select></div><div class="col-md-8"><input name="reason" class="form-control form-control-sm" placeholder="Reason when required"></div><div class="col-md-6"><input name="internal_note" value="{{ $scope->internal_note }}" class="form-control form-control-sm" placeholder="Internal note"></div><div class="col-md-6"><input name="customer_remark" value="{{ $scope->customer_remark }}" class="form-control form-control-sm" placeholder="Customer-visible remark"></div><div class="col-12"><button class="btn btn-sm btn-primary">Save Processing Progress</button></div></div></form>@endif @endunless
</article></div>@endforeach</div></div>@endforeach
@unless($locked)@if($scopes->isNotEmpty()&&$resolved===$scopes->count())<form method="POST" action="{{ route('admin.requests.processing.complete',$customerRequest) }}" class="border border-success rounded p-3 mt-3">@csrf @method('PATCH')<h3 class="h6">Complete Case</h3><div class="row g-2"><div class="col-md-3"><input type="date" name="completion_date" value="{{ now()->toDateString() }}" max="{{ now()->toDateString() }}" required class="form-control"></div><div class="col-md-3"><input name="customer_remark" class="form-control" placeholder="Customer-visible completion remark"></div><div class="col-md-4"><input name="internal_note" class="form-control" placeholder="Internal completion note"></div><div class="col-md-2"><button class="btn btn-success w-100">Complete Case</button></div></div></form>@endif @endunless
@endif</div></section>
