@php
    $accepted = $customerRequest->requestServices->where('status','approved');
    $scopes = $accepted->flatMap->workScopes;
    $resolved = $scopes->whereIn('status',['completed','cancelled'])->count();
    $locked = in_array($customerRequest->status,['completed','dispatched','delivered','closed','archived'],true);
@endphp
<div class="card border-0 shadow-sm mb-4" id="processing-checklist"><div class="card-body">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">Processing &amp; Work Checklist</h2><div class="text-muted small">{{ $resolved }} of {{ $scopes->count() }} resolved</div></div>@if(!$customerRequest->usesChecklistWorkflow())<span class="badge text-bg-secondary">Legacy Workflow</span>@endif</div>
<div class="row g-2 mb-3">@foreach([['Reference Number',$customerRequest->reference_no],['File Number',$customerRequest->file_number ?: 'Not assigned'],['Customer',$customerRequest->name],['Mobile',$customerRequest->mobile],['Accepted Services',$accepted->pluck('service_name_en_snapshot')->filter()->implode(', ')],['Payment',str($customerRequest->payment_status)->headline()],['Overall Status',str($customerRequest->status)->replace('_',' ')->headline()],['Estimated Completion',$customerRequest->estimated_completion_date?->format('d M Y') ?: 'Not configured']] as [$label,$value])<div class="col-6 col-lg-3"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value ?: '—' }}</strong></div>@endforeach</div>
@if(!$customerRequest->usesChecklistWorkflow())<div class="alert alert-secondary mb-0">This request uses the Legacy Workflow. Existing processing controls remain available.</div>
@elseif($processingEligibility['payment_pending'])<div class="alert alert-warning"><strong>Payment Pending.</strong> Payment must be confirmed before work processing can start.</div>
@elseif(!$processingEligibility['eligible'])<div class="alert alert-warning"><strong>Processing unavailable.</strong><ul class="mb-0">@foreach($processingEligibility['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul></div>
@elseif($locked)
<div class="alert alert-{{ $customerRequest->status==='completed' ? 'success' : 'secondary' }}">@if($customerRequest->status==='completed')Case processing is complete. Add dispatch or delivery details.@else Processing is read-only because the case is {{ str($customerRequest->status)->headline() }}.@endif</div>
@if($customerRequest->status==='completed')<form method="POST" action="{{ route('admin.requests.processing.reopen',$customerRequest) }}" class="row g-2 mb-3">@csrf @method('PATCH')<div class="col-md-9"><input name="reason" class="form-control" required placeholder="Required reopen reason"></div><div class="col-md-3"><button class="btn btn-outline-danger w-100">Reopen Case</button></div></form>@endif
@endif
@if($customerRequest->usesChecklistWorkflow())
@unless($locked)<div class="d-flex flex-wrap gap-2 mb-3">@foreach($accepted as $selectedService)<form method="POST" action="{{ route('admin.requests.processing.work-items.bulk',$customerRequest) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="start_service"><input type="hidden" name="request_service_id" value="{{ $selectedService->id }}"><button class="btn btn-sm btn-outline-primary">Start all Pending — {{ $selectedService->service_name_en_snapshot }}</button></form>@endforeach</div>@endunless
<form method="POST" action="{{ route('admin.requests.processing.work-items.bulk',$customerRequest) }}" class="mb-3">@csrf @method('PATCH')
@foreach($accepted as $selectedService)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between gap-2"><h3 class="h6">{{ $selectedService->service_name_en_snapshot }}@if($selectedService->service_name_gu_snapshot) / {{ $selectedService->service_name_gu_snapshot }}@endif</h3></div>
@foreach($selectedService->workScopes as $scope)<div class="row g-2 align-items-start border-top py-2"><div class="col-auto pt-2">@unless($locked)<input class="form-check-input" type="checkbox" name="work_scope_ids[]" value="{{ $scope->id }}">@endunless</div><div class="col-md-3"><strong>{{ $scope->name_en_snapshot }}</strong>@if($scope->name_gu_snapshot)<small class="d-block text-muted">{{ $scope->name_gu_snapshot }}</small>@endif</div><div class="col-md-2"><span class="badge text-bg-{{ ['pending'=>'secondary','in_progress'=>'primary','completed'=>'success','cancelled'=>'warning'][$scope->status] ?? 'secondary' }}">{{ $scope->status==='cancelled' ? 'Not Required' : str($scope->status)->replace('_',' ')->headline() }}</span></div><div class="col"><small class="d-block">{{ $scope->customer_remark }}</small><small class="text-muted">{{ $scope->internal_note }}</small></div></div>@endforeach</div>@endforeach
@unless($locked)<div class="row g-2"><div class="col-md-3"><select name="action" class="form-select" required><option value="">Bulk action…</option><option value="complete">Mark Completed</option><option value="cancel">Mark Not Required</option><option value="note">Add Internal Note</option></select></div><div class="col-md-3"><input name="reason" class="form-control" placeholder="Reason (required to cancel)"></div><div class="col-md-4"><input name="internal_note" class="form-control" placeholder="Common internal note"></div><div class="col-md-2"><button class="btn btn-primary w-100">Apply</button></div></div>@endunless</form>
@unless($locked)@foreach($scopes as $scope)<form method="POST" action="{{ route('admin.requests.processing.work-items.update',[$customerRequest,$scope]) }}" class="border rounded p-2 mb-2">@csrf @method('PATCH')<div class="row g-2"><div class="col-md-3"><strong>{{ $scope->name_en_snapshot }}</strong></div><div class="col-md-2"><select name="status" class="form-select" @disabled($scope->status==='completed')>@foreach(['pending'=>'Pending','in_progress'=>'In Progress','completed'=>'Completed','cancelled'=>'Not Required'] as $value=>$label)<option value="{{ $value }}" @selected($scope->status===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><input name="reason" class="form-control" placeholder="Cancel reason"></div><div class="col-md-2"><input name="internal_note" class="form-control" value="{{ $scope->internal_note }}" placeholder="Internal note"></div><div class="col-md-2"><input name="customer_remark" class="form-control" value="{{ $scope->customer_remark }}" placeholder="Customer remark"></div><div class="col-md-1"><button class="btn btn-outline-primary w-100" @disabled($scope->status==='completed')>Save</button></div></div></form>@if($scope->status==='completed')<form method="POST" action="{{ route('admin.requests.processing.work-items.reopen',[$customerRequest,$scope]) }}" class="row g-2 mb-2">@csrf @method('PATCH')<div class="col"><input name="reason" required class="form-control form-control-sm" placeholder="Required reason to reopen {{ $scope->name_en_snapshot }}"></div><div class="col-auto"><button class="btn btn-sm btn-outline-danger">Reopen Item</button></div></form>@endif @endforeach
@if($scopes->isNotEmpty() && $scopes->whereNotIn('status',['completed','cancelled'])->isEmpty() && !$accepted->contains(fn($service)=>$service->status==='under_review'))<form method="POST" action="{{ route('admin.requests.processing.complete',$customerRequest) }}" class="border border-success rounded p-3 mt-3">@csrf @method('PATCH')<h3 class="h6">Complete Case</h3><div class="row g-2"><div class="col-md-3"><input type="date" name="completion_date" value="{{ now()->toDateString() }}" max="{{ now()->toDateString() }}" required class="form-control"></div><div class="col-md-3"><input name="customer_remark" class="form-control" placeholder="Customer-visible completion remark"></div><div class="col-md-4"><input name="internal_note" class="form-control" placeholder="Internal completion note"></div><div class="col-md-2"><button class="btn btn-success w-100">Complete Case</button></div></div></form>@endif
@endunless
@endif
</div></div>
