@php($editing = isset($user))
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Name</label><input id="name" name="name" value="{{ old('name', $user->name ?? '') }}" class="form-control @error('name') is-invalid @enderror" maxlength="100" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="username">Username</label><input id="username" name="username" value="{{ old('username', $user->username ?? '') }}" class="form-control @error('username') is-invalid @enderror" maxlength="50" autocomplete="username" required>@error('username')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">Email <span class="text-muted">(optional)</span></label><input id="email" type="email" name="email" value="{{ old('email', $user->email ?? '') }}" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="mobile">Mobile Number</label><input id="mobile" name="mobile" value="{{ old('mobile', $user->mobile ?? '') }}" class="form-control @error('mobile') is-invalid @enderror" inputmode="numeric" pattern="[6-9][0-9]{9}" maxlength="10" autocomplete="tel" required><div class="form-text">10-digit Indian mobile number</div>@error('mobile')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="role">Role</label><select id="role" name="role" class="form-select @error('role') is-invalid @enderror" required>@foreach(config('permissions.labels') as $value=>$label)<option value="{{ $value }}" @selected(old('role', $user->role ?? 'staff') === $value)>{{ $label }}</option>@endforeach</select>@error('role')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 d-flex align-items-end"><input type="hidden" name="is_active" value="0"><div class="form-check mb-2"><input id="is_active" class="form-check-input" type="checkbox" name="is_active" value="1" @checked((bool)old('is_active', $user->is_active ?? true))><label for="is_active" class="form-check-label">Active account</label></div></div>
    @unless($editing)
        <div class="col-md-6"><label class="form-label" for="password">Password</label><input id="password" type="password" name="password" class="form-control @error('password') is-invalid @enderror" autocomplete="new-password" required>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="password_confirmation">Confirm Password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-control" autocomplete="new-password" required></div>
    @endunless
</div>
