@extends('layouts.admin')
@section('title','Government Charge Types')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h2 mb-1">Government Charge Types</h1><p class="text-muted mb-0">Reusable statutory charge labels. Request billing stores an immutable snapshot.</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5">Add Charge Type</h2><form method="POST" action="{{ route('admin.government-charge-types.store') }}" class="row g-2">@csrf
<div class="col-md-3"><input name="name_en" class="form-control" placeholder="English label" required></div><div class="col-md-3"><input name="name_gu" class="form-control" placeholder="Gujarati label"></div><div class="col-md-2"><input name="default_amount" type="number" min="0" step="0.01" value="0" class="form-control" required></div><div class="col-md-1"><input name="sort_order" type="number" min="0" value="0" class="form-control" required></div><div class="col-md-2"><input type="hidden" name="is_active" value="0"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked> Active</label></div><div class="col-md-1"><button class="btn btn-primary">Add</button></div></form></div></div>
<div class="vstack gap-3">@foreach($types as $type)<form method="POST" action="{{ route('admin.government-charge-types.update',$type) }}" class="card shadow-sm"><div class="card-body row g-2 align-items-center">@csrf @method('PUT')
<div class="col-md-3"><input name="name_en" value="{{ $type->name_en }}" class="form-control" required></div><div class="col-md-3"><input name="name_gu" value="{{ $type->name_gu }}" class="form-control"></div><div class="col-md-2"><input name="default_amount" value="{{ $type->default_amount }}" type="number" min="0" step="0.01" class="form-control"></div><div class="col-md-1"><input name="sort_order" value="{{ $type->sort_order }}" type="number" min="0" class="form-control"></div><div class="col-md-2"><input type="hidden" name="is_active" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($type->is_active)> Active</label></div><div class="col-md-1"><button class="btn btn-outline-primary">Save</button></div></div></form>@endforeach</div>
@endsection
