@extends('layouts.app')
@section('title','Book Appointment | Sai Consulting')
@section('content')
<section class="py-5"><div class="container" style="max-width:850px"><div class="card shadow-sm border-0"><div class="card-body p-4 p-lg-5"><h1 class="h2">Book Appointment <small class="d-block text-muted fs-5">મુલાકાતનો સમય લો</small></h1><p class="text-muted">Your request remains pending until our team confirms it.</p>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('appointments.store') }}" id="appointmentForm">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label">Customer Name / ગ્રાહકનું નામ</label><input class="form-control" name="customer_name" value="{{ old('customer_name') }}" required maxlength="120"></div><div class="col-md-6"><label class="form-label">Mobile Number</label><input class="form-control" name="mobile" value="{{ old('mobile') }}" inputmode="numeric" pattern="[6-9][0-9]{9}" required></div>
<div class="col-md-6"><label class="form-label">WhatsApp Number (optional)</label><input class="form-control" name="whatsapp" value="{{ old('whatsapp') }}" inputmode="numeric" pattern="[6-9][0-9]{9}"></div><div class="col-md-6"><label class="form-label">Email Address (optional)</label><input class="form-control" type="email" name="email" value="{{ old('email') }}"></div>
<div class="col-12"><label class="form-label">Service / સેવા</label><select class="form-select" name="service_id" id="service" required><option value="">Select service</option>@foreach($services as $s)<option value="{{ $s->id }}" @selected(old('service_id')==$s->id)>{{ $s->name_en }} @if($s->name_gu)/ {{ $s->name_gu }}@endif</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Appointment Date</label><input class="form-control" type="date" name="appointment_date" id="date" min="{{ now('Asia/Kolkata')->toDateString() }}" max="{{ now('Asia/Kolkata')->addMonths(6)->toDateString() }}" value="{{ old('appointment_date') }}" required></div><div class="col-md-6"><label class="form-label">Available Time Slot</label><select class="form-select" name="appointment_time" id="slot" required disabled><option value="">Select service and date</option></select><div id="slotHelp" class="form-text"></div></div>
<div class="col-12"><label class="form-label">Short Note / Purpose (optional)</label><textarea class="form-control" name="customer_note" maxlength="1000" rows="3">{{ old('customer_note') }}</textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="declaration" value="1" id="declaration" required><label class="form-check-label" for="declaration">I confirm these details are correct / આપેલી વિગતો સાચી છે.</label></div></div><div class="col-12"><button class="btn btn-primary btn-lg" type="submit">Request Appointment</button></div></div></form></div></div></div></section>
@endsection
@push('scripts')<script>const service=document.querySelector('#service'),date=document.querySelector('#date'),slot=document.querySelector('#slot'),help=document.querySelector('#slotHelp');async function loadSlots(){if(!service.value||!date.value){slot.disabled=true;return}slot.disabled=true;slot.innerHTML='<option>Loading...</option>';help.textContent='';try{const r=await fetch(`{{ route('appointments.availability') }}?date=${encodeURIComponent(date.value)}&service_id=${encodeURIComponent(service.value)}`,{headers:{Accept:'application/json'}});const d=await r.json();slot.innerHTML='<option value="">Select a time</option>';d.slots.forEach(s=>slot.add(new Option(s.label,s.value)));slot.disabled=!d.slots.length;help.textContent=d.slots.length?'':'No slots available for this date.'}catch(e){slot.innerHTML='<option value="">Unable to load slots</option>';help.textContent='Please try again.'}}service.addEventListener('change',loadSlots);date.addEventListener('change',loadSlots);if(service.value&&date.value)loadSlots();</script>@endpush
