@extends('layouts.app')
@section('title', 'વિનંતીની સ્થિતિ તપાસો | Track Request | Sai Consulting')
@section('description', 'તમારા રેફરન્સ નંબર અથવા ફાઇલ નંબર અને મોબાઇલ નંબરથી Sai Consulting વિનંતીની સ્થિતિ સુરક્ષિત રીતે તપાસો.')
@section('content')
@php
    $statusLabels = ['received'=>['વિનંતી મળી','Received'],'under_review'=>['ચકાસણી હેઠળ','Under Review'],'need_documents'=>['વધુ દસ્તાવેજો જરૂરી','Need Documents'],'approved'=>['મંજૂર','Approved'],'rejected'=>['નામંજૂર','Rejected'],'payment_pending'=>['ચુકવણી બાકી','Payment Pending'],'payment_received'=>['ચુકવણી મળી','Payment Received'],'draft_in_progress'=>['ડ્રાફ્ટ પ્રક્રિયામાં','Draft in Progress'],'ready_for_verification'=>['ચકાસણી માટે તૈયાર','Ready for Verification'],'customer_approved'=>['ગ્રાહક દ્વારા મંજૂર','Customer Approved'],'ready_for_registration'=>['નોંધણી માટે તૈયાર','Ready for Registration'],'dispatched'=>['મોકલી આપેલ','Dispatched'],'completed'=>['પૂર્ણ','Completed'],'archived'=>['આર્કાઇવ કરેલ','Archived']];
    $statusColors = ['received'=>'primary','under_review'=>'info','need_documents'=>'warning','approved'=>'success','rejected'=>'danger','payment_pending'=>'warning','payment_received'=>'success','draft_in_progress'=>'info','ready_for_verification'=>'primary','customer_approved'=>'success','ready_for_registration'=>'primary','dispatched'=>'secondary','completed'=>'success','archived'=>'dark'];
    $paymentLabels = ['not_required'=>['જરૂરી નથી','Not Required'],'pending'=>['બાકી','Pending'],'received'=>['મળી','Received'],'partial'=>['આંશિક ચૂકવણી','Partially Paid']];
@endphp
<section class="tracking-page-hero py-5"><div class="container py-lg-4"><div class="row align-items-center g-4"><div class="col-lg-7"><span class="eyebrow"><span></span>Secure Request Tracking</span><h1>તમારી વિનંતીની સ્થિતિ તપાસો</h1><p>રેફરન્સ નંબર અથવા મંજૂરી પછી મળેલ ફાઇલ નંબર અને અરજી વખતે આપેલો મોબાઇલ નંબર દાખલ કરો.</p></div><div class="col-lg-5"><div class="tracking-privacy-card"><i class="bi bi-shield-lock"></i><div><strong>તમારી માહિતી સુરક્ષિત છે</strong><span>Only matching request information and customer-visible updates are displayed.</span></div></div></div></div></div></section>
<div class="tracking-page-body py-5"><div class="container">
    <div class="row justify-content-center"><div class="col-xl-10">
        @if($errors->any())<div class="alert alert-danger d-flex gap-2" role="alert"><i class="bi bi-exclamation-circle-fill"></i><span>{{ $errors->first() }}</span></div>@endif
        <form method="POST" action="{{ route('request.track.lookup') }}" class="tracking-lookup-card premium-card mb-5">@csrf
            <div class="tracking-form-heading"><span class="icon-box"><i class="bi bi-search"></i></span><div><h2>વિનંતી શોધો <small>Find Your Request</small></h2><p>Both numbers use the format shown below.</p></div></div>
            <div class="row g-3 align-items-end"><div class="col-lg-5"><label for="reference_no" class="form-label">રેફરન્સ / ફાઇલ નંબર <span>Reference / File Number</span></label><input id="reference_no" name="reference_no" value="{{ old('reference_no') }}" placeholder="SC/2026/000001 or SC/2026/F000001" class="form-control form-control-lg @error('reference_no') is-invalid @enderror" autocomplete="off" required>@error('reference_no')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-4"><label for="mobile" class="form-label">મોબાઇલ નંબર <span>Mobile Number</span></label><input id="mobile" name="mobile" value="{{ old('mobile') }}" inputmode="numeric" maxlength="10" class="form-control form-control-lg @error('mobile') is-invalid @enderror" required>@error('mobile')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-3"><button class="btn btn-primary btn-lg rounded-pill w-100" type="submit"><i class="bi bi-search me-1"></i> સ્થિતિ તપાસો</button></div></div>
        </form>
        @isset($customerRequest)
            @php($dispatchUpdate = $customerRequest->statusHistory->firstWhere('to_status', 'dispatched'))
            <section class="tracking-result" aria-labelledby="tracking-result-title">
                <div class="tracking-result-header"><div><span>Verified Request</span><h2 id="tracking-result-title">{{ $customerRequest->name }}</h2><p>{{ $customerRequest->service->name_gu }} <small>{{ $customerRequest->service->name_en }}</small></p></div><span class="tracking-status-badge text-bg-{{ $statusColors[$customerRequest->status] ?? 'secondary' }}"><i class="bi bi-circle-fill"></i><strong>{{ $statusLabels[$customerRequest->status][0] ?? str($customerRequest->status)->headline() }}</strong><small>{{ $statusLabels[$customerRequest->status][1] ?? '' }}</small></span></div>
                <div class="row g-4 mt-1"><div class="col-lg-8">
                    <div class="tracking-summary premium-card mb-4"><div class="row g-0"><div class="col-sm-6 tracking-summary-item"><i class="bi bi-hash"></i><span><small>Reference Number</small><strong>{{ $customerRequest->reference_no }}</strong></span></div>@if($customerRequest->file_number)<div class="col-sm-6 tracking-summary-item"><i class="bi bi-folder-check"></i><span><small>File Number</small><strong>{{ $customerRequest->file_number }}</strong></span></div>@endif<div class="col-sm-6 tracking-summary-item"><i class="bi bi-credit-card"></i><span><small>ચુકવણી · Payment</small><strong>{{ $paymentLabels[$customerRequest->payment_status][0] ?? str($customerRequest->payment_status)->headline() }} <em>{{ $paymentLabels[$customerRequest->payment_status][1] ?? '' }}</em></strong></span></div>@if($customerRequest->estimated_completion_date)<div class="col-sm-6 tracking-summary-item"><i class="bi bi-calendar-check"></i><span><small>Estimated Completion</small><strong>{{ $customerRequest->estimated_completion_date->format('d M Y') }}</strong></span></div>@endif<div class="col-sm-6 tracking-summary-item"><i class="bi bi-clock-history"></i><span><small>Last Updated</small><strong>{{ ($customerRequest->last_status_changed_at ?? $customerRequest->updated_at)->format('d M Y') }}</strong></span></div></div></div>
                    <div class="tracking-timeline-card premium-card"><div class="tracking-card-title"><span class="icon-box"><i class="bi bi-signpost-split"></i></span><div><h3>સ્થિતિ સમયરેખા</h3><p>Status Timeline</p></div></div><div class="public-status-timeline">@forelse($customerRequest->statusHistory->sortBy('created_at') as $history)<article class="public-timeline-item"><span class="timeline-dot text-bg-{{ $statusColors[$history->to_status] ?? 'secondary' }}"><i class="bi bi-check2"></i></span><div><div class="d-flex flex-wrap justify-content-between gap-2"><h4>{{ $statusLabels[$history->to_status][0] ?? str($history->to_status)->headline() }} <small>{{ $statusLabels[$history->to_status][1] ?? '' }}</small></h4><time>{{ $history->created_at->format('d M Y, g:i A') }}</time></div>@if($history->remarks)<p>{{ $history->remarks }}</p>@endif</div></article>@empty<article class="public-timeline-item"><span class="timeline-dot text-bg-primary"><i class="bi bi-check2"></i></span><div><h4>{{ $statusLabels[$customerRequest->status][0] ?? str($customerRequest->status)->headline() }} <small>{{ $statusLabels[$customerRequest->status][1] ?? '' }}</small></h4><time>{{ ($customerRequest->last_status_changed_at ?? $customerRequest->updated_at)->format('d M Y, g:i A') }}</time></div></article>@endforelse</div></div>
                </div><aside class="col-lg-4">
                    @if($customerRequest->service->requiredDocuments->isNotEmpty())<div class="tracking-side-card premium-card mb-4"><div class="tracking-card-title"><span class="icon-box"><i class="bi bi-files"></i></span><div><h3>જરૂરી દસ્તાવેજો</h3><p>Required Documents</p></div></div><ul class="tracking-document-list">@foreach($customerRequest->service->requiredDocuments as $document)<li><i class="bi bi-file-earmark-check"></i><span><strong>{{ $document->name_gu }}</strong><small>{{ $document->name_en }}</small></span></li>@endforeach</ul><div class="tracking-document-note"><i class="bi bi-info-circle"></i> Upload additional documents only when requested by Sai Consulting.</div></div>@endif
                    @if($dispatchUpdate || in_array($customerRequest->status, ['dispatched','completed','archived'], true))<div class="dispatch-card premium-card mb-4"><i class="bi bi-send-check"></i><span><small>Dispatch Information</small><strong>તમારી સેવા મોકલી આપવામાં આવી છે.</strong>@if($dispatchUpdate)<em>{{ $dispatchUpdate->created_at->format('d M Y, g:i A') }}</em>@endif @if($dispatchUpdate?->remarks)<p>{{ $dispatchUpdate->remarks }}</p>@endif</span></div>@endif
                    @if($whatsappUrl)<div class="tracking-help-card premium-card"><span class="icon-box"><i class="bi bi-whatsapp"></i></span><h3>મદદની જરૂર છે?</h3><p>Need help understanding your request status?</p><a href="{{ $whatsappUrl }}" target="_blank" rel="noopener" class="btn btn-whatsapp-outline rounded-pill w-100 justify-content-center">WhatsApp Help</a></div>@endif
                </aside></div>
            </section>
        @endisset
    </div></div>
</div></div>
@endsection
